---
title: "cell_marker"
output: html_document
date: "2024-08-07"
---

# load libraries and set data directory
```{r}
library(Seurat)
library(SeuratObject)
library(ggplot2)
library(tidyverse)
```

# make Seurat object
```{r}
# set data directory
data_dir <- "/Users/taylaalbertini/Desktop/R studio/honours_project/placenta_spatial_annotating/outs"

# check data is there
list.files(data_dir) # Should show filtered_feature_bc_matrix.h5

# seu for Seurat
seu <- Load10X_Spatial(data.dir = data_dir, slice='sample1')
View(seu)
View(seu@meta.data)

# View image in Seurat object
SpatialPlot(seu, pt.size.factor = 1.3, alpha = 1) + 
  NoLegend() + 
  ggtitle('my Visium data') + 
  theme(plot.title = element_text(hjust = 0.5))
```

# data QC and violin plot
```{r}
## nCount = no of molecules / transcripts
## nFeature = no of genes
## MT = mitochondrial

# calculate % MT content per spot
# capital MT for human data. Lower case mt for mouse
seu <- PercentageFeatureSet(seu, "^MT-", col.name = "percent_mito")

head(seu) # a new column should now be there called "percent_mito"

# Vln plot QC data
VlnPlot(seu, features = c("nCount_Spatial", "nFeature_Spatial", "percent_mito"), 
        pt.size = 0.1, 
        group.by = 'orig.ident') + NoLegend()

seu # check dimensions of object

## QC Trim objects individually
# filter data. Change these values based on your data and the violin plots
seu_fil <- subset(seu, subset = nCount_Spatial > 800 & 
                    nFeature_Spatial > 500 & 
                    percent_mito < 10)

# Vln again after filtering
VlnPlot(seu_fil, features = c("nCount_Spatial", "nFeature_Spatial", "percent_mito"), 
        pt.size = 0.1, 
        group.by = 'orig.ident') + NoLegend()

## see where there are high counts in the image 
SpatialFeaturePlot(seu, features = "nCount_Spatial") +
  SpatialFeaturePlot(seu_fil, features = "nCount_Spatial") 

seu_fil
```

# pre-processing using Seurat
```{r}
## Seurat Workflow
seu_fil <- NormalizeData(seu_fil) ## normalise the data
seu_fil <- FindVariableFeatures(seu_fil) ## find the variable features
seu_fil <- ScaleData(seu_fil) ## scale the data
seu_fil <- RunPCA(seu_fil) # run linear dimensional reduction
seu_fil <- FindNeighbors(seu_fil, dims = 1:30) # find neighbours in order to cluster data 
seu_fil <- FindClusters(seu_fil, resolution = 0.9)  # need to use optimal resolution to cluster data so that transitioning cells or similar cells are not clumped together
seu_fil <- RunUMAP(seu_fil, dims = 1:30, n.neighbors = 50)

# visualise the data
DimPlot(seu_fil, reduction = "umap", group.by = "seurat_clusters", label = T)

# check whether resolution used to process data was optimal 
## use clusters 0, 1 and 4 to make a new dim plot
cells <- CellsByIdentities(seu_fil, idents = c(2, 3, 4))
SpatialDimPlot(seu_fil, cells.highlight = cells[setdiff(names(cells), "NA")], # check spatially where the clusters are (what tissue)
               cols.highlight = c("yellow", "grey50"),
               facet.highlight = T, combine = T)
## can use the spatial feature plot function to look at the spatial expression of a specific gene
SpatialFeaturePlot(seu_fil, features = "ACTG2")
## visualise myometrium, decidua and placenta cell gene markers in the cluster
FeaturePlot(object = seu_fil, 
            features = c("DES", "PRL", "CGA"), label = T, raster = FALSE)

SpatialFeaturePlot(seu_fil, features = "CYP19A1") + # gene marker for syncytiotrophoblasts (SCTs)
  SpatialFeaturePlot(seu_fil, features = "ERVW-1") # gene marker for villous cytotrophobasts (VCTs) + SCTs

SpatialFeaturePlot(seu_fil, features = "MME") + # gene symbol for fetal placenta SCT and VCT cells from GSEA database
SpatialFeaturePlot(seu_fil, features = "STAB2") # gene symbol for fetal placenta EVT cells from GSEA database
```

# identify marker genes
```{r}
# identify marker genes
markers <- FindAllMarkers(seu_fil, assay = "Spatial", only.pos = TRUE) 
# subset for the top marker genes for each cluster
markers %>%
  group_by(cluster) %>%
  dplyr::filter(avg_log2FC > 1) %>%
  slice_head(n = 10) %>%
  ungroup() -> top10
```

# load known marker CellMarker2.0 files 
```{r}
# Amnion-like cells
amnion_like_data <- read.csv(file = file.path("/Users/taylaalbertini/Desktop/CellMaker/amnion_like_cell.csv"), sep = ",", header = TRUE)

# Cytotrophoblast cell
cytotrophoblast_data <- read.csv(file = file.path("/Users/taylaalbertini/Desktop/CellMaker/cytotrophoblast_cell.csv"), sep = ",", header = TRUE)

# Decidual cell 
decidual_data <- read.csv(file = file.path("/Users/taylaalbertini/Desktop/CellMaker/decidual_cell.csv"), sep = ",", header = TRUE)

# Dendritic cell
dendritic_data <- read.csv(file = file.path("/Users/taylaalbertini/Desktop/CellMaker/dendritic_cell.csv"), sep = ",", header = TRUE)

# Epithelial cell
epithelial_data <- read.csv(file = file.path("/Users/taylaalbertini/Desktop/CellMaker/epithelial_cell.csv"), sep = ",", header = TRUE)

# EVT cell
evt_data <- read.csv(file = file.path("/Users/taylaalbertini/Desktop/CellMaker/extravillous_trophoblast.csv"), sep = ",", header = TRUE)

# M2 Macrophage cell
m2_macrophage_data <- read.csv(file = file.path("/Users/taylaalbertini/Desktop/CellMaker/m2_macrophage_cell.csv"), sep = ",", header = TRUE)

# Macrophage cell
macrophage_data <- read.csv(file = file.path("/Users/taylaalbertini/Desktop/CellMaker/macrophage.csv"), sep = ",", header = TRUE)

# Mesenchymal Stem cell
mesenchymal_stem_data <- read.csv(file = file.path("/Users/taylaalbertini/Desktop/CellMaker/mesenchymal_stem_cell.csv"), sep = ",", header = TRUE)

# Mesenchymal Stromal cell
mesenchymal_stromal_data <- read.csv(file = file.path("/Users/taylaalbertini/Desktop/CellMaker/mesenchymal_stromal_cell.csv"), sep = ",", header = TRUE)

# Monocyte Derived Macrophage cell
monocyte_derived_macrophage_data <- read.csv(file = file.path("/Users/taylaalbertini/Desktop/CellMaker/monocyte_derived_macrophage.csv"), sep = ",", header = TRUE)

# Monocyte cell
monocyte_data <- read.csv(file = file.path("/Users/taylaalbertini/Desktop/CellMaker/monocyte.csv"), sep = ",", header = TRUE)

# Natural Killer Cell
natural_killer_data <- read.csv(file = file.path("/Users/taylaalbertini/Desktop/CellMaker/natural_killer_cell.csv"), sep = ",", header = TRUE)

# Neutrophil cell
neutrophil_data <- read.csv(file = file.path("/Users/taylaalbertini/Desktop/CellMaker/neutrophil_cell.csv"), sep = ",", header = TRUE)

# RBC
rbc_data <- read.csv(file = file.path("/Users/taylaalbertini/Desktop/CellMaker/red_blood_cell.csv"), sep = ",", header = TRUE)

# Regulatory T cell
regulatory_t_data <- read.csv(file = file.path("/Users/taylaalbertini/Desktop/CellMaker/regulatory_t_cell.csv"), sep = ",", header = TRUE)

# Stem cell
stem_data <- read.csv(file = file.path("/Users/taylaalbertini/Desktop/CellMaker/stem_cell.csv"), sep = ",", header = TRUE)

# Syncytiotrophoblast cell
syncytiotrophoblast_data <- read.csv(file = file.path("/Users/taylaalbertini/Desktop/CellMaker/syncytiotrophoblast.csv"), sep = ",", header = TRUE)

# T cell
t_data <- read.csv(file = file.path("/Users/taylaalbertini/Desktop/CellMaker/t_cell.csv"), sep = ",", header = TRUE)

# Trophoectoderm cell
trophoectoderm_data <- read.csv(file = file.path("/Users/taylaalbertini/Desktop/CellMaker/trophectoderm_cell.csv"), sep = ",", header = TRUE)

# Trophoblast cell
trophoblast_data <- read.csv(file = file.path("/Users/taylaalbertini/Desktop/CellMaker/trophoblast_cell.csv"), sep = ",", header = TRUE)

# Vascular Endothelial cell
vendothelial_data <- read.csv(file = file.path("/Users/taylaalbertini/Desktop/CellMaker/vascular_endothelial_cell.csv"), sep = ",", header = TRUE)

# Vascular Smooth Muscle
vsmooth_muscle_data <- read.csv(file = file.path("/Users/taylaalbertini/Desktop/CellMaker/vascular_smooth_muscle_cell.csv"), sep = ",", header = TRUE)

# VCT cell
villous_cyto_data <- read.csv(file = file.path("/Users/taylaalbertini/Desktop/CellMaker/villous_cytotrophoblast.csv"), sep = ",", header = TRUE)

# Villous Stromal cell
villous_stromal_data <- read.csv(file = file.path("/Users/taylaalbertini/Desktop/CellMaker/villous_stromal_cell.csv"), sep = ",", header = TRUE)
```

# make geneSymbol lists
```{r}
amnion <- amnion_like_data$marker
cyto <-cytotrophoblast_data$marker
decidual <- decidual_data$marker
dendritic <- dendritic_data$marker
epithelial <- epithelial_data$marker
evt <- evt_data$marker
m2_macro <- m2_macrophage_data$marker
macro <- macrophage_data$marker
mesenchymal_stem <- mesenchymal_stem_data$marker
mesenchymal_stromal <- mesenchymal_stromal_data$marker
monocyte <- monocyte_data$marker
monocyte_derived_macrophage <- monocyte_derived_macrophage_data$marker
natural_killer <- natural_killer_data$marker
neutrophil <- neutrophil_data$marker
rbc <- rbc_data$marker
reg_t <- regulatory_t_data$marker
stem <- stem_data$marker
sct <- syncytiotrophoblast_data$marker
t_cell <- t_data$marker
trophoblast <- trophoblast_data$marker
trophoectoderm <- trophoectoderm_data$marker
vct <- villous_cyto_data$marker
villous_stromal <- villous_stromal_data$marker
vsmooth <- vsmooth_muscle_data$marker
```

# Compare gene markers to known gene markers
```{r}
known_markers <- data.frame(
  cell_type = c("Amnion-like cell","Cytotrophoblast cell", "Decidual cell", "Dendritic cell", "Epithelial cell", "Extravillous Trophoblast cell", "M2 Macrophage cell", "Macrophage cell", "Mesenchymal Stem cells", "Mesenchymal Stromal cell", "Monocyte cell", "Monocyte-derived Macrophage cell", "Natural Killer cell", "Neutrophil cell", "RBC", "Regulatory T cell", "Syncytiotrophoblast cell", "Stem cell", "T cell", "Trophoblast cell", "Trophoectoderm cell", "Villous Cytotrophoblast cell", "Villous Stromal cell", "Villous Smooth Muscle cell"),
  marker_genes = I(list(
    amnion,
    cyto,
    decidual,
    dendritic,
    epithelial,
    evt,
    m2_macro,
    macro,
    mesenchymal_stem,
    mesenchymal_stromal,
    monocyte,
    monocyte_derived_macrophage,
    natural_killer,
    neutrophil,
    rbc,
    reg_t,
    stem,
    sct,
    t_cell,
    trophoblast,
    trophoectoderm,
    vct,
    villous_stromal,
    vsmooth 
  ))
)
print(known_markers)

# Function to match clusters to known cell types using a list of gene symbols
annotate_clusters <- function(markers, known_markers) {
  cluster_annotations <- list()
  for (cluster in unique(markers$cluster)) {
    cluster_genes <- markers %>% filter(cluster == !!cluster) %>% pull(gene)
    matched_cell_types <- list()
    for (i in 1:nrow(known_markers)) {
      if (any(cluster_genes %in% known_markers$marker_genes[[i]])) {
        matched_cell_types <- c(matched_cell_types, known_markers$cell_type[i])
      }
    }
    cluster_annotations[[as.character(cluster)]] <- unique(matched_cell_types)
  }
  return(cluster_annotations)
}

# annotate clusters
cluster_annotations <- annotate_clusters(top10, known_markers)

# print annotations
print(cluster_annotations)
```

# annotate Seurat Object based on the cluster annotations
```{r}
# create names vector of cluster annotations
cluster_labels <- sapply(cluster_annotations, function(x) paste(unique(x), collapse = ", "))
print(cluster_labels)

# add c;uster labels to Seurat object
seu_fil$cell_type <- seu_fil$seurat_clusters %>%
  as.character() %>%
  map_chr(~ cluster_labels[.])
print(seu_fil@meta.data$cell_type)

# Visualize the annotations
DimPlot(seu_fil, reduction = "umap", group.by = "cell_type")

SpatialDimPlot(seu_fil, group.by = "cell_type")
```
