---
title: "depletedM_plots"
output: html_document
date: "2024-07-04"
---

# load libraries and set project directory 
```{r}
# load relevant libraries 
library(plyr)
library(reshape2)
library(dplyr)
library(stringr)
library(readxl)
library(readr)
library(magrittr)
library(ggplot2)
library(edgeR)
library(limma)
library(Glimma)
library(RColorBrewer)
library(ComplexHeatmap)
library(ggrepel)

# set project directory
projectDir <- "/Users/taylaalbertini/Desktop/R studio/honours_project/fetal_comparison/readCounts_analysis/rawData"

# set path for data tables 
import_placentaM_depleted <- file.path(projectDir, "placentaM_depleted.csv")
import_meanM_ncpms <- file.path(projectDir, "mean_male_cpms_TMM.csv")
```

# import data files
```{r}
# import male placenta depleted transcript table
placentaM_depleted <- read_delim(file = import_placentaM_depleted,
                                 col_names = TRUE,
                                 delim = ",") %>%
  as.data.frame() %>%
  ## remove the first column "...1" that;s input when the file is imported
  dplyr::select(., -...1)

# import ncpms of all male tissues
ncpms_male <- read_delim(file = file.path(projectDir, "mean_male_cpms_TMM.csv"),
                           col_names = TRUE,
                           delim = ",") %>%
  as.data.frame() %>%
  ## remove the first column "...1" that;s input when the file is imported
  dplyr::select(., -...1)
```

# heat map of depleted genes
```{r}
# transform the ncpms table so that 'ensembl' are rownames and sex_tissue are columns with ncpms
ncpms_male_2 <- t(ncpms_male) %>%
  data.frame() %>%
  tibble::rownames_to_column("ensembl")

# tidy table
## remove placenta counts
ncpms_male_2 <- ncpms_male_2[,-7]
## rename column names
colnames(ncpms_male_2) <- gsub("X1", "Male Brain", colnames(ncpms_male_2))
colnames(ncpms_male_2) <- gsub("X2", "Male Heart", colnames(ncpms_male_2))
colnames(ncpms_male_2) <- gsub("X3", "Male Liver", colnames(ncpms_male_2))
colnames(ncpms_male_2) <- gsub("X4", "Male Lung", colnames(ncpms_male_2))
colnames(ncpms_male_2) <- gsub("X5", "Male Muscle", colnames(ncpms_male_2))
## remove sex_tissue row
ncpms_male_2 <- ncpms_male_2[-1,]

# subset placentaF_depleted to only include ncpms_TMM for placenta and corresponding ensembl IDs
depleted_placentaM <- dplyr::select(placentaM_depleted, ensembl, nCPM_placenta_TMM)

# left join ncpms_male_2 to depleted_placentaM
heat_plot <- dplyr::left_join(depleted_placentaM, ncpms_male_2, by = join_by(ensembl))


## replace placenta colname 
colnames(heat_plot) <- gsub("nCPM_placenta_TMM", "Male Placenta", colnames(heat_plot))
## put ncpms in descending order
heat_plot_ordered <- heat_plot[order(heat_plot$`Male Placenta`, decreasing = TRUE),]
## make heat_plot_ordered numeric
heat_plot_ordered$`Male Brain` <- as.numeric(heat_plot_ordered$`Male Brain`)
heat_plot_ordered$`Male Heart` <- as.numeric(heat_plot_ordered$`Male Heart`)
heat_plot_ordered$`Male Liver` <- as.numeric(heat_plot_ordered$`Male Liver`)
heat_plot_ordered$`Male Lung` <- as.numeric(heat_plot_ordered$`Male Lung`)
heat_plot_ordered$`Male Muscle` <- as.numeric(heat_plot_ordered$`Male Muscle`)
## change order so that placenta is last
heat_plot_ordered <- dplyr::relocate(heat_plot_ordered, `Male Placenta`, .after = `Male Muscle`)
rownames(heat_plot_ordered) <- NULL
pheat_plot <- tibble::column_to_rownames(heat_plot_ordered, var = "ensembl")

# Heatmap function to visualise the matrix as a heatmap with default settings
## make my df a matrix
class(pheat_plot)
mat <- as.matrix(pheat_plot)
class(mat)

## column splot
column_split_vector <- c(rep("Group 1", 5), "Group 2")

## craete box plot annotation
column_ha <- HeatmapAnnotation(`log10 (nCPMs)` = anno_boxplot(log10(mat), which = c("column"), height = unit(4, "cm")))

## craete heatmap with annotation
heatmapM = Heatmap(log10(mat), 
             column_split = column_split_vector,
             column_title = "Tissues", 
             column_title_gp = gpar(fontsize = 12),
             column_title_side = c("bottom"),
             #row_title = "Genes", 
             row_title_gp = gpar(fontsize = 12),
             show_row_names = FALSE,
             show_heatmap_legend = FALSE,
             #column_names_rot = 45,
             column_names_gp = gpar(fontsize = 10),
             cluster_rows = FALSE,
             cluster_columns = FALSE,
             width = unit(3.5, "cm"),
             name = "log10 (nCPM)",
             border = "black",
             show_column_names = FALSE,
             bottom_annotation = column_ha)
## prints the heatmap
heatmapM

# export heatmap as jpeg 
path_save <- "/Users/taylaalbertini/Desktop/depletedM_heatmap_update.jpeg"

jpeg(path_save, width = 4000, height = 3500, res = 400)
draw(heatmapM)
dev.off()
```

# scatter plot of depleted male genes
```{r}
# read in annotated data
annot_depleted <- read_delim(file = file.path(projectDir, "placentaM_depleted_annotated.csv"),
                             col_names = TRUE,
                             delim = ",") %>%
  as.data.frame() %>%
  ## remove the first column "...1" that;s input when the file is imported
  dplyr::select(., -...1)

# make an effect size column
annot_depleted$effect_size <- annot_depleted$nCPM_5_TMM - annot_depleted$nCPM_placenta_TMM

# subset annot_depleted to include hgnc symbols, TMM normalised ncpms and nCPM_ratio_TMM
scatter <- dplyr::select(annot_depleted, hgnc_symbol, nCPM_placenta_TMM, nCPM_ratio_TMM, effect_size)

# order by nCPM_ratio_TMM - descending 
scatter_ordered <- scatter[order(scatter$nCPM_ratio_TMM, decreasing = TRUE),]

# convert hgnc_symbol from a column to row names 
rownames(scatter_ordered) <- NULL
scatter_plot <- tibble::column_to_rownames(scatter_ordered, var = "hgnc_symbol")

# create a scatter plot where x-axis = nCPMs and y-axis = nCPM_ratio using ggplot2
ggplot(data = scatter_plot,
       aes(x = nCPM_placenta_TMM,
           y = nCPM_ratio_TMM)) +
  
  geom_point(#size = scatter_plot$effect_size * 0.05,
             color = "black", 
             shape = 1) +
  
  labs(x = "Normalised Counts Per Million", 
       y = "nCPM(rank=5)/nCPM(rank=6)") +
  
  scale_y_continuous(breaks = c(pretty(range(scatter_plot$y)), 3, 50, 100, 150)) +
 
   ## forces the bottom of the y-axis to be set at 0
  coord_cartesian(ylim = c(0, max(scatter_plot$nCPM_ratio_TMM) + max(scatter_plot$effect_size) * 0.1), expand = FALSE) +
  
  ## annotates/labels the ten-greatest nCPM ratio genes 
  geom_text_repel(data = subset(scatter_plot, nCPM_ratio_TMM > 34),
            aes(label = rownames(subset(scatter_plot, nCPM_ratio_TMM > 34))),
            nudge_y = 20,
            size          = 2.5,
            box.padding   = 1.5,
            point.padding = 0.5,
            force         = 100,
            segment.size  = 0.2,
            segment.color = "grey50",
            direction     = "x") +
  
  theme_bw() +
  
  theme(plot.title = element_text(size = 10))

# saves the last plot printed in working dir
ggsave("maleplot.png", width = 7, height = 7, units = "in") 
```

