---
title: "depletedF_plots"
output: html_document
date: "2024-07-04"
---

# load libraries and set project directory 
```{r}
# load relevant libraries 
library(plyr)
library(reshape2)
library(dplyr)
library(stringr)
library(readxl)
library(readr)
library(magrittr)
library(ggplot2)
library(edgeR)
library(limma)
library(Glimma)
library(RColorBrewer)
library(ComplexHeatmap)
library(ggrepel)

# set project directory
projectDir <- "/Users/taylaalbertini/Desktop/R studio/honours_project/fetal_comparison/readCounts_analysis/rawData"

# set path for data tables 
import_placentaF_depleted <- file.path(projectDir, "placentaF_depleted.csv")
import_meanF_ncpms <- file.path(projectDir, "mean_female_cpms_TMM.csv")
```

# load data files
```{r}
# import female placenta depleted transcript table
placentaF_depleted <- read_delim(file = import_placentaF_depleted,
                           col_names = TRUE,
                           delim = ",") %>%
  as.data.frame() %>%
  ## remove the first column "...1" that;s input when the file is imported
  dplyr::select(., -...1)

# import ncpms of all female tissues
ncpms_female <- read_delim(file = import_meanF_ncpms,
                           col_names = TRUE,
                           delim = ",") %>%
  as.data.frame() %>%
  ## remove the first column "...1" that;s input when the file is imported
  dplyr::select(., -...1)
```

# heatmap of female placenta depleted genes
```{r}
# pre-process input data frame 
## transform ncpm table so that 'ensembl' are row names and sex_tissue are columns with ncpms
ncpms_female_2 <- t(ncpms_female) %>%
  data.frame() %>%
  tibble::rownames_to_column("ensembl")

## tidy table
## remove placenta counts
ncpms_female_2 <- ncpms_female_2[,-7]
## rename column names
colnames(ncpms_female_2) <- gsub("X1", "Female Brain", colnames(ncpms_female_2))
colnames(ncpms_female_2) <- gsub("X2", "Female Heart", colnames(ncpms_female_2))
colnames(ncpms_female_2) <- gsub("X3", "Female Liver", colnames(ncpms_female_2))
colnames(ncpms_female_2) <- gsub("X4", "Female Lung", colnames(ncpms_female_2))
colnames(ncpms_female_2) <- gsub("X5", "Female Muscle", colnames(ncpms_female_2))
## remove sex_tissue row
ncpms_female_2 <- ncpms_female_2[-1,]

## subset placentaF_depleted to only include ncpms_TMM for placenta and corresponding ensembl IDs
depleted_placentaF <- dplyr::select(placentaF_depleted, ensembl, nCPM_placenta_TMM)

## left join ncpms_female_2 to depleted_placentaF
heat_plot <- dplyr::left_join(depleted_placentaF, ncpms_female_2, by = join_by(ensembl))

## replace placenta colname 
colnames(heat_plot) <- gsub("nCPM_placenta_TMM", "Female Placenta", colnames(heat_plot))
## put ncpms in descending order
heat_plot_ordered <- heat_plot[order(heat_plot$`Female Placenta`, decreasing = TRUE),]
## make heat_plot_ordered numeric
heat_plot_ordered$`Female Brain` <- as.numeric(heat_plot_ordered$`Female Brain`)
heat_plot_ordered$`Female Heart` <- as.numeric(heat_plot_ordered$`Female Heart`)
heat_plot_ordered$`Female Liver` <- as.numeric(heat_plot_ordered$`Female Liver`)
heat_plot_ordered$`Female Lung` <- as.numeric(heat_plot_ordered$`Female Lung`)
heat_plot_ordered$`Female Muscle` <- as.numeric(heat_plot_ordered$`Female Muscle`)
## change order so that placenta is last
heat_plot_ordered <- dplyr::relocate(heat_plot_ordered, `Female Placenta`, .after = `Female Muscle`)
rownames(heat_plot_ordered) <- NULL
pheat_plot <- tibble::column_to_rownames(heat_plot_ordered, var = "ensembl")

# Heatmap function to visualise the matrix as a heatmap with default settings
## make my df a matrix
class(pheat_plot)
mat <- as.matrix(pheat_plot)

## column splot
column_split_vector <- c(rep("Group 1", 5), "Group 2")
## craete box plot annotation
column_ha <- HeatmapAnnotation(`log10 (nCPMs)` = anno_boxplot(log10(mat), which = c("column"), height = unit(4, "cm")), annotation_name_side = "left")

## craete heatmap with annotation
heatmapF <- Heatmap(log10(mat), 
        column_split = column_split_vector,
        column_title = "Tissues", 
        column_title_gp = gpar(fontsize = 12),
        column_title_side = c("bottom"),
        row_title = "Genes", 
        row_title_gp = gpar(fontsize = 12),
        show_row_names = FALSE,
        #column_names_rot = 45,
        column_names_gp = gpar(fontsize = 10),
        cluster_rows = FALSE,
        cluster_columns = FALSE,
        width = unit(3.5, "cm"),
        name = "log10 (nCPM)",
        border = "black",
        show_heatmap_legend = FALSE,
        show_column_names = FALSE,
        bottom_annotation = column_ha)
## print heatmap 
heatmapF

# export heatmap as jpeg 
path_save <- "/Users/taylaalbertini/Desktop/depletedF_heatmap_update.jpeg"
jpeg(path_save, width = 4000, height = 3500, res = 400)
draw(heatmapF)
dev.off()
```

# depleted transcript scatter plot
```{r}
# read in annotated data
annot_depleted <- read_delim(file = file.path(projectDir, "placentaF_depleted_annotated.csv"),
                             col_names = TRUE,
                             delim = ",") %>%
  as.data.frame() %>%
  ## remove the first column "...1" that;s input when the file is imported
  dplyr::select(., -...1)

# make an effect size column
annot_depleted$effect_size <- annot_depleted$nCPM_5_TMM - annot_depleted$nCPM_placenta_TMM

# subset annot_depleted to include hgnc symbols, TMM normalised ncpms and nCPM_ratio_TMM
scatter <- dplyr::select(annot_depleted, hgnc_symbol, nCPM_placenta_TMM, nCPM_ratio_TMM, effect_size)

# order by nCPM_ratio_TMM - descending 
scatter_ordered <- scatter[order(scatter$nCPM_ratio_TMM, decreasing = TRUE),]

# convert hgnc_symbol from a column to row names 
rownames(scatter_ordered) <- NULL
scatter_plot <- tibble::column_to_rownames(scatter_ordered, var = "hgnc_symbol")

# create a scatter plot where x-axis = nCPMs and y-axis = nCPM_ratio using ggplot2
ggplot(data = scatter_plot,
       aes(x = nCPM_placenta_TMM,
           y = nCPM_ratio_TMM)) +
  
  geom_point(color = "black",
             shape = 1) +
  
  labs(x = "Normalised Counts Per Million", 
       y = "nCPM(rank=5)/nCPM(rank=6)") +
  
  scale_y_continuous(breaks = c(pretty(range(scatter_plot$y)), 3, 50, 100, 150, 200, 250)) +
  
  coord_cartesian(ylim = c(0, max(scatter_plot$nCPM_ratio_TMM) + max(scatter_plot$effect_size) * 0.1), expand = FALSE) +
 
  ## annotates/labels the ten-greatest nCPM ratio genes 
  geom_text_repel(data = subset(scatter_plot, nCPM_ratio_TMM > 37), 
            aes(label = rownames(subset(scatter_plot, nCPM_ratio_TMM > 37))),
            nudge_y = 20,
            size          = 2.5,
            box.padding   = 1.5,
            point.padding = 0.5,
            force         = 100,
            segment.size  = 0.2,
            segment.color = "grey50",
            direction     = "x") +
  
  theme_bw() + ## sets the plot background theme to black and white
  
  theme(plot.title = element_text(size = 10)) ## sets the text size 

# export the last graph printed
ggsave("femaleplot.png", width = 7, height = 7, units = "in") 
```

# sanity plot for DESq vs TMM normalisation techniques
```{r}
# set project directory
path <- "/Users/taylaalbertini/Desktop/R studio/honours_project/fetal_comparison/readCounts_analysis/rawData"

# set path for female TMM normalised ncpm counts
import_mean_female_cpms_TMM <- file.path(path, "mean_female_cpms_TMM.csv")
# set path for female DESq normalised ncpm counts
import_mean_female_cpms_DESq <- file.path(path, "mean_female_cpms_DESq.csv")

## import data
# import mean female cpms table
ncpms_female_TMM <- read_delim(file = import_mean_female_cpms_TMM,
                                   col_names = TRUE,
                                   delim = ",") %>%
  as.data.frame() %>%
  # remove the first column "...1" that;s input when the file is imported
  dplyr::select(., -...1)

# import mean female cpms table
ncpms_female_DESq <- read_delim(file = import_mean_female_cpms_DESq,
                                   col_names = TRUE,
                                   delim = ",") %>%
  as.data.frame() %>%
  # remove the first column "...1" that;s input when the file is imported
  dplyr::select(., -...1)

# transform the tables
# TMM
ncpms_TMM <- t(ncpms_female_TMM) %>%
  data.frame() %>%
  tibble::rownames_to_column("ensembl")
## rename column names
colnames(ncpms_TMM) <- gsub("X1", "female_brain_TMM", colnames(ncpms_TMM))
colnames(ncpms_TMM) <- gsub("X2", "female_heart_TMM", colnames(ncpms_TMM))
colnames(ncpms_TMM) <- gsub("X3", "female_liver_TMM", colnames(ncpms_TMM))
colnames(ncpms_TMM) <- gsub("X4", "female_lung_TMM", colnames(ncpms_TMM))
colnames(ncpms_TMM) <- gsub("X5", "female_muscle_TMM", colnames(ncpms_TMM))
colnames(ncpms_TMM) <- gsub("X6", "female_placenta_TMM", colnames(ncpms_TMM))
## remove sex_tissue row
ncpms_TMM <- ncpms_TMM[-1,]

# DESeq2
ncpms_DESq <- t(ncpms_female_DESq) %>%
  data.frame() %>%
  tibble::rownames_to_column("ensembl")
## rename column names
colnames(ncpms_DESq) <- gsub("X1", "female_brain_DESq", colnames(ncpms_DESq))
colnames(ncpms_DESq) <- gsub("X2", "female_heart_DESq", colnames(ncpms_DESq))
colnames(ncpms_DESq) <- gsub("X3", "female_liver_DESq", colnames(ncpms_DESq))
colnames(ncpms_DESq) <- gsub("X4", "female_lung_DESq", colnames(ncpms_DESq))
colnames(ncpms_DESq) <- gsub("X5", "female_muscle_DESq", colnames(ncpms_DESq))
colnames(ncpms_DESq) <- gsub("X6", "female_placenta_DESq", colnames(ncpms_DESq))
## remove sex_tissue row
ncpms_DESq <- ncpms_DESq[-1,]

# subset brain
brain_TMM <- dplyr::select(ncpms_TMM, ensembl, female_brain_TMM) 
brain_Desq <- dplyr::select(ncpms_DESq, ensembl, female_brain_DESq)

# join the two normalised tables together
norm_plot <- dplyr::left_join(brain_TMM, brain_Desq, by = join_by("ensembl"))
## set ensembl column to row names
rownames(brain_TMM) <- NULL
brain_TMM <- tibble::column_to_rownames(brain_TMM, var = "ensembl")

# create scatter plot with slope line
ggplot(data = norm_plot,
       aes(x = female_brain_TMM,
           y = female_brain_DESq)) +
  geom_point(alpha = 0.3) +
  geom_abline(slope = 1, intercept = 0, linetype = "dashed", color = "red") +
  theme_minimal() +
  labs(title = "Comparison of Normalized Counts",
       x = "TMM Normalized CountsDESeq2 Normalized Counts",
       y = "DESeq2 Normalized Counts") +
  theme(plot.title = element_text(hjust = 0.5),
        axis.text.x = element_blank(),  # Hides x-axis label
        axis.text.y = element_blank())  # Hides y-axis label)
```
