---
title: "norm_combined_heartM"
output: html_document
---

# load libraries and set project directory 
```{r}
library(plyr)
library(reshape2)
library(dplyr)
library(stringr)
library(readxl)
library(readr)
library(magrittr)
library(ggplot2)
library(edgeR)
library(limma)
library(Glimma)
library(RColorBrewer)

# set project directory
projectDir <- "/Users/taylaalbertini/Desktop/R studio/honours_project/fetal_comparison/tissue_depletion/rawData"

# path for data tables 
import_TMM_depletedM <- file.path(projectDir, "TMM_heartM_depleted.csv")
import_DESq_depletedM <- file.path(projectDir, "DESq_heartM_depleted.csv")
```

# import data tables 
```{r}
# TMM_depletedM
TMM_depletedM <- read_delim(file = import_TMM_depletedM,
                            col_names = TRUE,
                            delim = ",") %>%
  as.data.frame() %>%
  # remove the first column "...1" that;s input when the file is imported
  dplyr::select(., -...1)

# DESq_depletedM
DESq_depletedM <- read_delim(file = import_DESq_depletedM,
                             col_names = TRUE,
                             delim = ",") %>%
  as.data.frame() %>%
  # remove the first column "...1" that;s input when the file is imported
  dplyr::select(., -...1)
```

# fulfilment of criteria (1) and (2) for TMM and DESq2 normalisation 
```{r}
# filter the df to only including the relevant pieces of information and make specific to normalisation technique
## TMM 
## remove rank column
TMM_depletedM <- TMM_depletedM[,-3]
## rename columns to be specific to TMM normalisation
colnames(TMM_depletedM) <- gsub("tissue", "tissue_r5_TMM", colnames(TMM_depletedM))
colnames(TMM_depletedM) <- gsub("nCPM_5", "nCPM_5_TMM", colnames(TMM_depletedM))
colnames(TMM_depletedM) <- gsub("nCPM_6", "nCPM_heart_TMM", colnames(TMM_depletedM))
colnames(TMM_depletedM) <- gsub("nCPM_ratio", "nCPM_ratio_TMM", colnames(TMM_depletedM))
colnames(TMM_depletedM) <- gsub("geneid", "ensembl", colnames(TMM_depletedM))

## DESq
## remove rank column
DESq_depletedM <- DESq_depletedM[,-3]
## rename columns to be specific to DESq normalisation
colnames(DESq_depletedM) <- gsub("tissue", "tissue_r5_DESq", colnames(DESq_depletedM))
colnames(DESq_depletedM) <- gsub("nCPM_5", "nCPM_5_DESq", colnames(DESq_depletedM))
colnames(DESq_depletedM) <- gsub("nCPM_6", "nCPM_heart_DESq", colnames(DESq_depletedM))
colnames(DESq_depletedM) <- gsub("nCPM_ratio", "nCPM_ratio_DESq", colnames(DESq_depletedM))
colnames(DESq_depletedM) <- gsub("geneid", "ensembl", colnames(DESq_depletedM))
      
# test to ensure there are no duplicated ensembl names
sum(duplicated(TMM_depletedM$ensembl))
sum(duplicated(DESq_depletedM$ensembl))
        
# left join TMM_depletedM to DESq_depletedM
heartM_depleted <- dplyr::inner_join(TMM_depletedM, DESq_depletedM, by = join_by(ensembl))
## export for plots
write.csv(heartM_depleted, file = file.path(projectDir, "heartM_depleted.csv"))
```
