---
title: "earlyF_enrichmentAnalysis"
output: html_document
date: "2024-05-17"
---

# load libraries
```{r}
library(stringr)
library(magrittr)
library(ggplot2)
library(RColorBrewer)

# set project directory
projectDir <- "/Users/taylaalbertini/Desktop/R studio/honours_project/oxygen_threshold/rawData"
import_placentaF_depleted <- file.path(projectDir, "early_placentaF_depleted_annotated.csv")
import_placentaM_depleted <- file.path(projectDir, "early_placentaM_depleted_annotated.csv")
```

# install ggkegg
```{r}
# install ggkegg, scatterpie and tidygraph packages if don't already have 
# load libraries
library(ggkegg)
library(tidygraph)
library(scatterpie)
library(dplyr)
library(readxl)
library(readr)
library(edgeR)
library(limma)
library(Glimma)
library(clusterProfiler)
library(enrichplot)
```

# import files
```{r}
# import placenta female depleted table and make it into a data frame
placentaF_depleted <- read_delim(import_placentaF_depleted,
                                 col_names = TRUE,
                                 delim = ",") %>%
  as.data.frame() 
  ## tidy placentaF_depleted - remove the "...1" column
  placentaF_depleted <- dplyr::select(placentaF_depleted, -...1)

# import male placenta depleted table and make into a data frame
placentaM_depleted <- read_delim(import_placentaM_depleted,
                                 col_names = TRUE,
                                 delim = ",") %>%
  as.data.frame()
  ## tidy placentaM_depleted - remove the "...1" column
  placentaM_depleted <- dplyr::select(placentaM_depleted, -...1)
```

# pathway analysis using enrichKEGG for female samples
```{r}
# convert ensembl IDs into entrez IDs
## install and load libraries neede for conversion
library("org.Hs.eg.db")
library("AnnotationDbi")
## perform conversion
### convert ensembl to rownames
placentaF_entrez <- tibble::column_to_rownames(placentaF_depleted, var = "ensembl")
entrez_ids <- mapIds(org.Hs.eg.db, keys = rownames(placentaF_entrez), keytype="ENSEMBL", column = "ENTREZID") %>%
as.data.frame()
### change colname from "." to ENTREZID
colnames(entrez_ids) <- gsub(".", "ENTREZID", colnames(entrez_ids))
### create a vector consisting of just the entrez ids
entrez_vector <- entrez_ids$ENTREZID

# perform functonal enrichment analysis using the tool enrichKEGG
## install clusterProfiler package which has enrichKEGG tool/function
library("clusterProfiler")
## run enrichKEGG function on entrez IDs
kegg_result <- enrichKEGG(entrez_vector, 
                          organism = "hsa",
                          keyType = "kegg", 
                          pvalueCutoff = 0.05, 
                          pAdjustMethod = "BH",
                          minGSSize = 10, 
                          maxGSSize = 500, 
                          qvalueCutoff = 0.2, 
                          use_internal_data = FALSE)
print(kegg_result)
head(kegg_result, 21)
```

# pathway analysis using enrichKEGG for male samples
```{r}
# convert ensembl IDs into entrez IDs
## install and load libraries neede for conversion
library("org.Hs.eg.db")
library("AnnotationDbi")
## perform conversion
### convert ensembl to rownames
placentaM_entrez <- tibble::column_to_rownames(placentaM_depleted, var = "ensembl")
entrezM_ids <- mapIds(org.Hs.eg.db, keys = rownames(placentaM_entrez), keytype="ENSEMBL", column = "ENTREZID") %>%
as.data.frame()
### change colname from "." to ENTREZID
colnames(entrezM_ids) <- gsub(".", "ENTREZID", colnames(entrezM_ids))
### create a vector consisting of just the entrez ids
entrezM_vector <- entrezM_ids$ENTREZID

# perform functonal enrichment analysis using the tool enrichKEGG
## install clusterProfiler package which has enrichKEGG tool/function
library("clusterProfiler")
## run enrichKEGG function on entrez IDs
kegg_result <- enrichKEGG(entrezM_vector, 
                          organism = "hsa",
                          keyType = "kegg", 
                          pvalueCutoff = 0.05, 
                          pAdjustMethod = "BH",
                          minGSSize = 10, 
                          maxGSSize = 500, 
                          qvalueCutoff = 0.2, 
                          use_internal_data = FALSE)
print(kegg_result)
head(kegg_result, 22)

# semantic reduction of KEGG analysis results
## install and load the package simplifyEnrichment 
library("simplifyEnrichment")

## create a vector of KEGG IDs
enrich_results_df <- as.data.frame(kegg_result)
head(enrich_results_df)
hsa_ID_vector <- enrich_results_df$ID %>%
  as.vector()

## clustering common terms from KEGG analysis
term_similarity_from_KEGG <- function(hsa_ID_vector) {
  # Placeholder function body
  # This is where you would calculate the term similarity
  return(data.frame(Term = hsa_ID_vector, Similarity = runif(length(hsa_ID_vector))))
}
  # Calculate term similarity from KEGG
  summarised_terms <- term_similarity_from_KEGG(hsa_ID_vector)

# simplify 
  simplified_terms <- tibble::column_to_rownames(summarised_terms, var = "Term") %>%
    as.matrix()
  colnames(simplified_terms) <- NULL
simpler_terms <- simplifyEnrichment(simplified_terms, cutoff = 0.7, select_fun = min)

```

# gprofiler2 functional enrichment analysis
```{r}
# install and laod library for gprofiler2
library(gprofiler2)

# female placenta enrichment analysis
## order genes by nCPM_ratio
placentaF_ordered <- placentaF_depleted[order(placentaF_depleted$nCPM_ratio_TMM, decreasing = TRUE),]
## perform enrichment analysis on ordered genes
placentaF_ordered_enriched <- gost(placentaF_ordered$ensembl, organism = "hsapiens",
                                   ordered_query = TRUE)
## visualise the GO terms
head(placentaF_ordered_enriched$result, 50)

# male placenta enrichment analysis
## order genes by nCPM_ratio
placentaM_ordered <- placentaM_depleted[order(placentaM_depleted$nCPM_ratio_TMM, decreasing = TRUE),]
## perform enrichment on ordered genes
placentaM_ordered_enriched <- gost(placentaM_ordered$ensembl, organism = "hsapiens",
                                   ordered_query = TRUE)
## visualise the GO terms
head(placentaM_ordered_enriched$result, 50)
```

# semantic reduction of GO terms
```{r}
# load simplifyEnrichment package
library(simplifyEnrichment)
library(org.Hs.eg.db)
library(Cairo)

# semantic reduction of female GO terms
## craete a similarity matrix of the GO terms 
### make a vector of GO IDs
go_id_vectorF <- placentaF_ordered_enriched$result$term_id %>%
  as.vector()
go_id_similarityMatrixF <- GO_similarity(go_id_vectorF, 
                     ont = "BP", 
                     db = "org.Hs.eg.db", 
                     measure = "Rel", 
                     remove_orphan_terms = FALSE)
## use the simplifyEnrichment tool to cluster the GO terms 
go_id_simplifiedF <- simplifyGO(mat = go_id_similarityMatrixF, 
                               method = "binary_cut", 
                               control = list(), 
                               plot = TRUE, 
                               column_title = "Female early-gestation placenta depleted GO terms",
                               verbose = TRUE) 


# semantic reduction of male GO terms
## craete a similarity matrix of the GO terms 
### make a vector of GO IDs
go_id_vectorM <- placentaM_ordered_enriched$result$term_id %>%
  as.vector()
go_id_similarityMatrixM <- GO_similarity(go_id_vectorM, 
                     ont = "BP", 
                     db = "org.Hs.eg.db", 
                     measure = "Rel", 
                     remove_orphan_terms = FALSE)
## use the simplifyEnrichment tool to cluster the GO terms 
go_id_simplifiedM <- simplifyGO(mat = go_id_similarityMatrixM, 
                               method = "binary_cut", 
                               control = list(), 
                               plot = TRUE, 
                               column_title = "Male early-gestation placenta depleted GO term semantic reduction",
                               verbose = TRUE)
```

# visualisation of enriched female placenta ensembls
```{r}
# female placenta plot
# visualise the enriched genes in a plot
gostplot(placentaF_ordered_enriched, interactive = TRUE)
# make a 'publishable plot with top 4 enriched genes highlighted
placentaF_enriched_plot <- gostplot(placentaF_ordered_enriched, interactive = FALSE)
publish_gostplot(placentaF_enriched_plot, highlight_terms = c("GO:0007154", "GO:0023052", "GO:0050896", "GO:0032501"))

# male placenta plot
placentaM_enriched_plot <- gostplot(placentaM_ordered_enriched, interactive = FALSE)
publish_gostplot(placentaM_enriched_plot, highlight_terms = c("GO:0007154", "GO:0023052", "GO:0050896", "GO:0007165"))
```

# export GO terms
```{r}
# female enriched GO terms export
## make placentaF_ordered_enriched$result a df
placentaF_enriched_export <- placentaF_ordered_enriched$result %>%
  as.data.frame()
## remove list column - parents
placentaF_enriched_export <- placentaF_enriched_export[,-14]
## export as a cvs
write.csv(placentaF_enriched_export, file = file.path(projectDir, "early_placentaF_enrichedPathways.csv"))

# male enriched GO terms export
## make placentaF_ordered_enriched$result a df
placentaM_enriched_export <- placentaM_ordered_enriched$result %>%
  as.data.frame()
## remove list column - parents
placentaM_enriched_export <- placentaM_enriched_export[,-14]
## export as a cvs
write.csv(placentaM_enriched_export, file = file.path(projectDir, "early_placentaM_enrichedPathways.csv"))
```
