---
title: "libsize_plot"
output: html_document
date: "2024-07-30"
---

# load libraries and set project directory 
```{r}
# load relevant libraries 
library(plyr)
library(reshape2)
library(dplyr)
library(stringr)
library(readxl)
library(readr)
library(magrittr)
library(ggplot2)
library(edgeR)
library(limma)
library(Glimma)
library(RColorBrewer)

# set project directory
projectDir <- "/Users/taylaalbertini/Desktop/R studio/honours_project/libsize"

# set path for data tables 
import_metadata <- file.path(projectDir, "library_size_metadata.csv")
import_fetal_rawcounts <- file.path(projectDir, "fetal_rawcounts.csv")
```

# import rawcount tables and meta data 
```{r}
# import meta data table 
metaData <- read_delim(file = import_metadata,
                       col_names = TRUE,
                       delim = ",") 
## remane "sampleID" to sample for consistency across tables
colnames(metaData) <- c("sample", "Tissue", "Sex", "Gestational Age")
## make first letter of all characters in "Tissue" and "Sex" column upper-case and change 
metaData %<>% dplyr::mutate(., Tissue = paste(str_to_title(Tissue))) %>% 
  dplyr::mutate(., Sex = paste(str_to_title(Sex))) %>% 
  dplyr::mutate(., Tissue = str_replace(Tissue, pattern = "_mid", replacement = " Mid")) %>% 
  dplyr::mutate(., Tissue = str_replace(Tissue, pattern = "_early", replacement = " Early")) %>% 
  dplyr::mutate(., Tissue = str_replace(Tissue, pattern = "_term", replacement = " Term"))

# import mid-gestation and other fetal tissue rawcounts table
mid_fetal <- read_delim(file = import_fetal_rawcounts,
                        col_names = TRUE,
                        delim = ",") 
## remane "...1" ensembl
colnames(mid_fetal) <- gsub("...1", "ensembl", colnames(mid_fetal), fixed = TRUE)

# import early-gestation placenta rawcounts tables
## female
earlyF <- read_delim(file = file.path("/Users/taylaalbertini/Desktop/R studio/honours_project/oxygen_threshold/rawData/rawCounts_placentaF_early.csv"),
                     col_names = TRUE,
                     delim = ",")
## remane "...1" ensembl
colnames(earlyF) <- gsub("...1", "ensembl", colnames(earlyF), fixed = TRUE)

## male
earlyM <- read_delim(file = file.path("/Users/taylaalbertini/Desktop/R studio/honours_project/oxygen_threshold/rawData/rawCounts_placentaM_early.csv"),
                     col_names = TRUE,
                     delim = ",")
## remane "...1" ensembl
colnames(earlyM) <- gsub("...1", "ensembl", colnames(earlyM), fixed = TRUE)

# import term placenta rawcounts tables
term <- read_delim(file = file.path("/Users/taylaalbertini/Desktop/R studio/honours_project/termPlacenta_comparison/rawData/rawCounts_term_placenta.csv"),
                     col_names = TRUE,
                     delim = ",")
## remane "...1" ensembl
colnames(term) <- gsub("...1", "ensembl", colnames(term), fixed = TRUE)
```


# merge rawcounts into one table
```{r}
total_rawCounts <- dplyr::full_join(mid_fetal, earlyF, by = "ensembl") %>% 
  dplyr::full_join(., earlyM, by = "ensembl") %>% 
                     dplyr::full_join(., term, by = "ensembl")

# check if any NA values were introduced
sum(is.na(total_rawCounts))
# replace NA values with zeros
total_rawCounts[is.na(total_rawCounts)] <- 0

# check for any duplications of ensembl IDs
sum(duplicated(total_rawCounts$ensembl))
```

# create library size table from rawcounts
```{r}
# make ensembl column row names
rownames(total_rawCounts) <- NULL
total_rawCounts %<>% tibble::column_to_rownames(., var = "ensembl")
# create a small data frame with information for the plot - sample name and total counts 
plotCounts <- total_rawCounts %>%
  colSums(.) %>%
  as.data.frame() %>%
  tibble::rownames_to_column() %>%
  set_colnames(c("sample", "totalCounts")) %>%
  arrange(., totalCounts)
```

# join metadata to library size table
```{r}
# left join libsize table to metadata by sample
heatplot <- dplyr::left_join(metaData, plotCounts, by = "sample") %>% 
  tibble::column_to_rownames(., var = "sample")

# check for any NA values and remove those rows
na_rows <- apply(heatplot, 1, function(x) any(is.na(x)))
heatplot <- heatplot[!na_rows, ]
```

# create a clustered heatmap for respective sample library sizes
```{r}
# load complexheatmap 
library(ComplexHeatmap)

# convert plotCounts into a matrix
mat <- as.matrix(plotCounts)
class(mat)

# create clustered heatmap
Heatmap(mat)

## pheat
library(pheatmap)
pheat_plot <- tibble::column_to_rownames(heatplot, var = "sample")
mat_2 <- as.matrix(pheat_plot)
class(mat_2
      )
heat <- pheatmap(mat_2,
                 cluster_cols = FALSE,
                 cluster_rows = FALSE)

# make a matrix with samples as rownames, tissue as a column and totalCounts as values
mat <- dplyr::select(heatplot, sample, tissue, totalCounts) %>% 
  tibble::column_to_rownames(., var = "sample") %>% 
  as.matrix()

# make a separate data frame with annotation info
annotation_row <- dplyr::select(heatplot, sample, sex) %>% 
  tibble::column_to_rownames(., var = "sample")

# set annotation colours
ann_colours <- list(
  sex = c(male = "blue", female = "pink")
)

# create the heatmap
heat <- pheatmap(mat,
                 annotation_row = annotation_row,
                 annotation_colors = ann_colours,
                 cluster_cols = FALSE,
                 clustering_method = "complete",
                 annotation_names_row = TRUE,
                 annotation_names_col = TRUE)


?heatmap

mat <- dplyr::select(heatplot, sample, totalCounts) %>% 
  tibble::column_to_rownames(., var = "sample") %>% 
  as.matrix()
heatmap(mat)

pheatmap(mat, 
         cluster_cols = FALSE,
         cluster_rows = FALSE,
         display_numbers = TRUE,
         main = "Heatmap of Lib Sizes")
annotation_row <- dplyr::select(heatplot, sample, sex) %>% 
  tibble::column_to_rownames(., var = "sample")
 
library(ComplexHeatmap)
Heatmap(
  mat,
  name = "Library Size",
  cluster_rows = FALSE,  # Do not cluster rows (only one row)
  cluster_columns = FALSE,  # Do not cluster columns
  show_row_names = FALSE,
  show_column_names = TRUE,
  row_title = "Samples"
)
```

# boxplot of library sizes
```{r}
library(hrbrthemes)
library(viridis)

# create boxplot using heatplot df 
ggplot(heatplot, aes(x = Tissue, y = totalCounts / 1e6, fill = Sex)) +
  geom_boxplot(position = position_dodge(width = 0.8), alpha = 0.7) +
  geom_point(position = position_dodge(width = 0.8), size = 2, color = "black", alpha = 0.6) +
  labs(x = "Tissue",
       y = "Total Counts (per million)") +
  theme_bw() +
  scale_fill_manual(values = c("Male" = "blue", "Female" = "pink")) +
  geom_hline(yintercept = 10000000 / 1e6,
             show.legend = FALSE,
             linetype = "dotted",
             color = "red") +
  geom_line(aes(y = 10000000 / 1e6, color = "Threshold"), linewidth = 1) +
  geom_hline(yintercept = 26255718 / 1e6,
             show.legend = FALSE,
             linetype = "dotted",
             color = "blue") +
  geom_line(aes(y = 26255718 / 1e6, color = "Mean"), linewidth = 1) +
  scale_color_manual(name = "Legend",
                     values = c("Mean" = "blue", "Threshold" = "red"),
                     labels = c("Mean library size", "Library size cut off")) +
  scale_y_continuous(breaks = c(10, 25, 50, 75, 100, 125))

ggsave("libsize_boxplot.png", width = 10, height = 7, units = "in") ## exportd the last graph printed
 ```

