---
title: "timeline"
output: html_document
date: "2024-08-02"
---

# load libraries and set project directory 
```{r}
# load relevant libraries 
library(plyr)
library(reshape2)
library(dplyr)
library(stringr)
library(readxl)
library(readr)
library(magrittr)
library(ggplot2)
library(edgeR)
library(limma)
library(Glimma)
library(RColorBrewer)

# set project directory
projectDir <- "/Users/taylaalbertini/Desktop/R studio/honours_project/libsize"
```

# create data frame
```{r}
gestation <- data.frame(weeks = 0:40,
                        what = "Gestation")
# assign gestation periods
gestation$gestation <- ifelse(gestation$weeks <= 12, "early-gestation",
                              ifelse(gestation$weeks <= 27, "mid-gestation", "third trimester"))
annotation_data <- data.frame(
  x = c(7, 20, 33), # midpoints for the gestation periods
  y = rep(0.8, 3), # y-values for annotations
  label = c("early-gestation", "mid-gestation", "third trimester")
)
# ggplot
ggplot(gestation, aes(
  x = weeks,
  y = what,
  label = weeks
)) +
  geom_line() +
  geom_segment(aes(x = weeks, xend = weeks, y = 0.99, yend = 1.03)) +
  geom_text(hjust = 0.5, angle = 0, vjust = -1.25) +
  scale_x_continuous(name = "Weeks", expand = c(0, 0.35)) +
  theme_bw() +
   theme(axis.text.y = element_blank(), 
        axis.ticks.y = element_blank()) +
  geom_text(data = annotation_data, aes(x = x, y = y, label = label), 
            hjust = 0.5, vjust = 1, angle = 0) 



# Add horizontal bracket lines
  geom_segment(data = annotation_data, aes(x = start, xend = end, y = 1.1, yend = 1.1)) +
  # Add vertical bracket lines at the start
  geom_segment(data = annotation_data, aes(x = start, xend = start, y = 1.05, yend = 1.1)) +
  # Add vertical bracket lines at the end
  geom_segment(data = annotation_data, aes(x = end, xend = end, y = 1.05, yend = 1.1)) +
  # Add gestation period labels above the brackets
  geom_text(data = annotation_data, aes(x = mid, y = 1.15, label = label), 
            hjust = 0.5, vjust = -0.5, angle = 0) +

```

