---
title: "male_depleted_plots"
output: html_document
date: "2024-07-04"
---

# load libraries and set project directory 
```{r}
# load relevant libraries 
library(plyr)
library(reshape2)
library(dplyr)
library(stringr)
library(readxl)
library(readr)
library(magrittr)
library(ggplot2)
library(edgeR)
library(limma)
library(Glimma)
library(RColorBrewer)

# set project directory
projectDir <- "/Users/taylaalbertini/Desktop/R studio/honours_project/sexSpecific_comparison/rawData"

# set path for data tables 
import_depletedM <- file.path(projectDir, "depleted_M.csv")
import_meanM_ncpms <- file.path(projectDir, "mean_placenta_cpms_TMM.csv")
```

# load data files
```{r}
# import male placenta depleted transcript table
placentaM_depleted <- read_delim(file = import_depletedM,
                           col_names = TRUE,
                           delim = ",") %>%
  as.data.frame() %>%
  ## remove the first column "...1" that;s input when the file is imported
  dplyr::select(., -...1)

# import ncpms of all male tissues
ncpms_male <- read_delim(file = import_meanM_ncpms,
                           col_names = TRUE,
                           delim = ",") %>%
  as.data.frame() %>%
  ## remove the first column "...1" that;s input when the file is imported
  dplyr::select(., -...1)
```

# heatmap of male placenta depleted genes
```{r}
# transform ncpm table so that 'ensembl' are rownames and sex_tissue are columns with ncpms
ncpms_male_2 <- t(ncpms_male) %>%
  data.frame() %>%
  tibble::rownames_to_column("ensembl")

# tidy table
## remove placenta counts
ncpms_male_2 <- ncpms_male_2[,-3]
## rename column names
colnames(ncpms_male_2) <- gsub("X1", "Mid-gestation Placenta (Female)", colnames(ncpms_male_2))
## remove sex_tissue row
ncpms_male_2 <- ncpms_male_2[-1,]

# subset placentaF_depleted to only include ncpms_TMM for placenta and corresponding ensembl IDs
depleted_placentaM <- dplyr::select(placentaM_depleted, ensembl, nCPM_male_placenta_TMM)

# left join ncpms_male_2 to depleted_placentaF
heat_plot <- dplyr::left_join(depleted_placentaM, ncpms_male_2, by = join_by(ensembl))

# tidy 
## replace placenta colname 
colnames(heat_plot) <- gsub("nCPM_male_placenta_TMM", "Mid-gestation Placenta (Male)", colnames(heat_plot))
## put ncpms in descending order
heat_plot_ordered <- heat_plot[order(heat_plot$`Mid-gestation Placenta (Male)`, decreasing = TRUE),]
## make heat_plot_ordered numeric
heat_plot_ordered$`Mid-gestation Placenta (Female)` <- as.numeric(heat_plot_ordered$`Mid-gestation Placenta (Female)`)
## change order so that placenta is last
heat_plot_ordered <- dplyr::relocate(heat_plot_ordered, `Mid-gestation Placenta (Male)`, .after = `Mid-gestation Placenta (Female)`)
rownames(heat_plot_ordered) <- NULL
pheat_plot <- tibble::column_to_rownames(heat_plot_ordered, var = "ensembl")

# complex heatmap
library(ComplexHeatmap)
library(circlize)
library(grid)

# Heatmap function to visualise the matrix as a heatmap with default settings
## make my df a matrix
class(pheat_plot)
mat <- as.matrix(pheat_plot)

## column splot
column_split_vector <- c(rep("Group 1", 1), "Group 2")

## craete box plot annotation
column_ha <- HeatmapAnnotation(`log10 (nCPMs)` = anno_boxplot(log10(mat), which = c("column"), height = unit(4, "cm")))

## print heatmap with annotation
heatmapM <- Heatmap(log10(mat), 
        column_split = column_split_vector,
        column_title = "Tissues", 
        column_title_gp = gpar(fontsize = 12),
        column_title_side = c("bottom"),
        #row_title = "Genes", 
        row_title_gp = gpar(fontsize = 12),
        show_row_names = FALSE,
        show_column_names = FALSE,
        column_names_gp = gpar(fontsize = 10),
        cluster_rows = FALSE,
        cluster_columns = FALSE,
        width = unit(2, "cm"),
        name = "log10 (nCPM)",
        border = "black",
        bottom_annotation = column_ha)

heatmapM

# export heatmap as jpeg 
path_save <- "/Users/taylaalbertini/Desktop/MidM_sex_specific_heatmap.jpeg"

jpeg(path_save, width = 4000, height = 3500, res = 400)
draw(heatmapM)
dev.off()
```
