---
title: "transcript_plots"
output: html_document
date: "2024-07-30"
---

# load libraries and set project directory 
```{r}
# load relevant libraries 
library(plyr)
library(reshape2)
library(dplyr)
library(stringr)
library(readxl)
library(readr)
library(magrittr)
library(ggplot2)
library(edgeR)
library(limma)
library(Glimma)
library(RColorBrewer)

# set project directory
projectDir <- "/Users/taylaalbertini/Desktop/R studio/honours_project/term_sex_specific_analysis/rawData"

# set path to data tables 
import_depletedF <- file.path(projectDir, "termF_depleted.csv")
import_depletedM <- file.path(projectDir, "termM_depleted.csv")
```

# load data files
```{r}
# import female placenta depleted transcript table
placentaF_depleted <- read_delim(file = import_depletedF,
                           col_names = TRUE,
                           delim = ",") %>%
  as.data.frame() %>%
  ## remove the first column "...1" that;s input when the file is imported
  dplyr::select(., -...1)

# import ncpms of all female tissues
placentaM_depleted <- read_delim(file = import_depletedM,
                           col_names = TRUE,
                           delim = ",") %>%
  as.data.frame() %>%
  ## remove the first column "...1" that;s input when the file is imported
  dplyr::select(., -...1)
```

# heatmap of female term placenta depleted transcripts 
```{r}
# subset placentaF_depleted to only include ncpms (TMM normalised) 
placentaF_depleted %<>% dplyr::select(., ensembl, nCPM_1_TMM, nCPM_termF_placenta_TMM) %>% 
  # arrange in descending order of female ncpms
  arrange(desc(nCPM_termF_placenta_TMM)) %>% 
  tibble::column_to_rownames(., var = "ensembl")
# clean up colnames 
colnames(placentaF_depleted) <- c("Male Placenta (term)", "Female Placenta (term)")

# complex heatmap
library(ComplexHeatmap)

# Heatmap function to visualise the matrix as a heatmap with default settings
## make my df a matrix
matF <- as.matrix(placentaF_depleted)
class(matF)

## column split vector
column_split_vector <- c(rep("Group 1", 1), "Group 2")
## craete box plot annotation
column_ha <- HeatmapAnnotation(`log10 (nCPMs)` = anno_boxplot(log10(matF + 0.001), which = c("column"), height = unit(4, "cm")))

## print heatmap with annotation
heatmapF <- Heatmap(log10(matF + 0.001), 
        column_split = column_split_vector,
        column_title = "Tissues", 
        column_title_gp = gpar(fontsize = 12),
        column_title_side = c("bottom"),
        row_title = "Genes", 
        row_title_gp = gpar(fontsize = 12),
        show_row_names = FALSE,
        column_names_rot = 45,
        column_names_gp = gpar(fontsize = 10),
        cluster_rows = FALSE,
        cluster_columns = FALSE,
        width = unit(2, "cm"),
        name = "log10 (nCPM)",
        border = "black",
        bottom_annotation = column_ha)
heatmapF

# export heatmap as jpeg 
path_save <- "/Users/taylaalbertini/Desktop/termF_depleted_heatmap.jpeg"

jpeg(path_save, width = 4000, height = 3500, res = 400)
draw(heatmapF)
dev.off()
```

# heatmap of male term placenta depleted transcripts 
```{r}
# subset placentaF_depleted to only include ncpms (TMM normalised) 
placentaM_depleted %<>% dplyr::select(., ensembl, nCPM_1_TMM, nCPM_termM_placenta_TMM) %>% 
  # arrange in descending order of female ncpms
  arrange(desc(nCPM_termM_placenta_TMM)) %>% 
  tibble::column_to_rownames(., var = "ensembl")
# clean up colnames 
colnames(placentaM_depleted) <- c("Female Placenta (term)", "Male Placenta (term)")

# complex heatmap
library(ComplexHeatmap)

# Heatmap function to visualise the matrix as a heatmap with default settings
## make my df a matrix
matM <- as.matrix(placentaM_depleted)
class(matM)

## column split vector
column_split_vector <- c(rep("Group 1", 1), "Group 2")
## craete box plot annotation
column_ha_m <- HeatmapAnnotation(`log10 (nCPMs)` = anno_boxplot(log10(matM), which = c("column"), height = unit(4, "cm")))

## print heatmap with annotation
heatmapM <- Heatmap(log10(matM), 
        column_split = column_split_vector,
        column_title = "Tissues", 
        column_title_gp = gpar(fontsize = 12),
        column_title_side = c("bottom"),
        row_title = "Genes", 
        row_title_gp = gpar(fontsize = 12),
        show_row_names = FALSE,
        column_names_rot = 45,
        column_names_gp = gpar(fontsize = 10),
        cluster_rows = FALSE,
        cluster_columns = FALSE,
        width = unit(2, "cm"),
        name = "log10 (nCPM)",
        border = "black",
        bottom_annotation = column_ha_m)
heatmapM

# export heatmap as jpeg 
path_save <- "/Users/taylaalbertini/Desktop/termM_depleted_heatmap.jpeg"

jpeg(path_save, width = 4000, height = 3500, res = 400)
draw(heatmapF)
dev.off()
```

