---
title: "sexComparison_enrichmentAnalysis"
output: html_document
date: "2024-05-27"
---

# load libraries
```{r}
library(stringr)
library(magrittr)
library(ggplot2)
library(RColorBrewer)
library(ggkegg)
library(tidygraph)
library(scatterpie)
library(dplyr)
library(readxl)
library(readr)
library(edgeR)
library(limma)
library(Glimma)
library(clusterProfiler)
library(enrichplot)

# set project directory
projectDir <- "/Users/taylaalbertini/Desktop/R studio/honours_project/sexSpecific_comparison/rawData"
import_placentaF_depleted <- file.path(projectDir, "placenta_female_depleted_annotated.csv")
import_placentaM_depleted <- file.path(projectDir, "placenta_male_depleted_annotated.csv")
```

# import files
```{r}
# import placenta female depleted table and make it into a data frame
placentaF_depleted <- read_delim(import_placentaF_depleted,
                                 col_names = TRUE,
                                 delim = ",") %>%
  as.data.frame() 
  ## tidy placentaF_depleted - remove the "...1" column
  placentaF_depleted <- dplyr::select(placentaF_depleted, -...1)

# import male placenta depleted table and make into a data frame
placentaM_depleted <- read_delim(import_placentaM_depleted,
                                 col_names = TRUE,
                                 delim = ",") %>%
  as.data.frame()
  ## tidy placentaM_depleted - remove the "...1" column
  placentaM_depleted <- dplyr::select(placentaM_depleted, -...1)
```

# pathway analysis using enrichKEGG for female samples
```{r}
# convert ensembl IDs into entrez IDs
## install and load libraries neede for conversion
library("org.Hs.eg.db")
library("AnnotationDbi")
## perform conversion
### convert ensembl to rownames
placentaF_entrez <- tibble::column_to_rownames(placentaF_depleted, var = "ensembl")
entrez_ids <- mapIds(org.Hs.eg.db, keys = rownames(placentaF_entrez), keytype="ENSEMBL", column = "ENTREZID") %>%
as.data.frame()
### change colname from "." to ENTREZID
colnames(entrez_ids) <- gsub(".", "ENTREZID", colnames(entrez_ids))
### create a vector consisting of just the entrez ids
entrez_vector <- entrez_ids$ENTREZID

# perform functonal enrichment analysis using the tool enrichKEGG
## install clusterProfiler package which has enrichKEGG tool/function
library("clusterProfiler")
## run enrichKEGG function on entrez IDs
kegg_result <- enrichKEGG(entrez_vector, 
                          organism = "hsa",
                          keyType = "kegg", 
                          pvalueCutoff = 0.05, 
                          pAdjustMethod = "BH",
                          minGSSize = 10, 
                          maxGSSize = 500, 
                          qvalueCutoff = 0.2, 
                          use_internal_data = FALSE)
print(kegg_result)
head(kegg_result, 21)
```

# pathway analysis using enrichKEGG for male samples
```{r}
# convert ensembl IDs into entrez IDs
## install and load libraries neede for conversion
library("org.Hs.eg.db")
library("AnnotationDbi")
## perform conversion
### convert ensembl to rownames
placentaM_entrez <- tibble::column_to_rownames(placentaM_depleted, var = "ensembl")
entrezM_ids <- mapIds(org.Hs.eg.db, keys = rownames(placentaM_entrez), keytype="ENSEMBL", column = "ENTREZID") %>%
as.data.frame()
### change colname from "." to ENTREZID
colnames(entrezM_ids) <- gsub(".", "ENTREZID", colnames(entrezM_ids))
### create a vector consisting of just the entrez ids
entrezM_vector <- entrezM_ids$ENTREZID

# perform functonal enrichment analysis using the tool enrichKEGG
## install clusterProfiler package which has enrichKEGG tool/function
library("clusterProfiler")
## run enrichKEGG function on entrez IDs
kegg_result <- enrichKEGG(entrezM_vector, 
                          organism = "hsa",
                          keyType = "kegg", 
                          pvalueCutoff = 0.05, 
                          pAdjustMethod = "BH",
                          minGSSize = 10, 
                          maxGSSize = 500, 
                          qvalueCutoff = 0.2, 
                          use_internal_data = FALSE)
print(kegg_result)
head(kegg_result, 21)
```

# gprofiler2 functional enrichment analysis
```{r}
# install and laod library for gprofiler2
#BiocManager::install("gprofiler2")
library(gprofiler2)

# order genes by nCPM_ratio
placentaF_ordered <- placentaF_depleted[order(placentaF_depleted$nCPM_ratio_TMM, decreasing = TRUE),]

# perform enrichment analysis on ordered genes
placentaF_ordered_enriched <- gost(placentaF_ordered$ensembl, organism = "hsapiens",
                                   ordered_query = TRUE,
                                   evcodes = TRUE)

head(placentaF_ordered_enriched$result, 50)

# investigate which genes were enriched in fatty acid oxidation related GO terms
go_term_of_interest <- "2-oxoglutarate-dependent dioxygenase activity"
enriched_row <- placentaF_ordered_enriched$result[placentaF_ordered_enriched$result$term_name == go_term_of_interest, ]
print(enriched_row$intersection)
```

```{r}
# order genes by nCPM_ratio
placentaM_ordered <- placentaM_depleted[order(placentaM_depleted$nCPM_ratio_TMM, decreasing = TRUE),]
# perform enrichment on ordered genes
placentaM_ordered_enriched <- gost(placentaM_ordered$ensembl, organism = "hsapiens",
                                   ordered_query = TRUE,
                                   evcodes = TRUE)
head(placentaM_ordered_enriched$result, 50)
```

# visualisation of enriched male placenta ensembls
```{r}
# female placenta plot
# visualise the enriched genes in a plot
gostplot(placentaF_ordered_enriched, interactive = TRUE)
# make a 'publishable plot with top 4 enriched genes highlighted
placentaF_enriched_plot <- gostplot(placentaF_ordered_enriched, interactive = FALSE)
publish_gostplot(placentaF_enriched_plot, highlight_terms = c("GO:0141052", "GO:0032452", "GO:0140457", "GO:0032451"))

# male placenta plot
placentaM_enriched_plot <- gostplot(placentaM_ordered_enriched, interactive = FALSE)
publish_gostplot(placentaM_enriched_plot, highlight_terms = c("GO:0008397", "GO:0033778", "GO:0007155", "GO:0033779"))
```

# export GO terms
```{r}
# female enriched GO terms export
## make placentaF_ordered_enriched$result a df
placentaF_enriched_export <- placentaF_ordered_enriched$result %>%
  as.data.frame()
## remove list column - parents
placentaF_enriched_export <- placentaF_enriched_export[,-14]
## export as a cvs
write.csv(placentaF_enriched_export, file = file.path(projectDir, "placentaF_sexComparison_enrichedPathways.csv"))

# male enriched GO terms export
## make placentaF_ordered_enriched$result a df
placentaM_enriched_export <- placentaM_ordered_enriched$result %>%
  as.data.frame()
## remove list column - parents
placentaM_enriched_export <- placentaM_enriched_export[,-14]
## export as a cvs
write.csv(placentaM_enriched_export, file = file.path(projectDir, "placentaM_sexComparison_enrichedPathways.csv"))
```

# rrvgo semantic reduction on midF GO terms
```{r}
#BiocManager::install("rrvgo")
library(rrvgo)
library(ComplexHeatmap)

# BP 
## create similarity matrix for GO terms of BP source
simMatrix_BP <- calculateSimMatrix(placentaF_ordered_enriched$result$term_id,
                                orgdb = "org.Hs.eg.db",
                                ont = "BP",
                                method = "Rel")
## set scores
scores <- setNames(-log10(placentaF_ordered_enriched$result$p_value), placentaF_ordered_enriched$result$term_id)
## reduce the number of terms based on the similarity matrix for BP terms
reducedTerms_BP <- reduceSimMatrix(simMatrix_BP,
                                threshold = 0.85,
                                orgdb = "org.Hs.eg.db",
                                scores)
## add the source to table
reducedTerms_BP$source <- "BP"

# MF 
## create similarity matrix for GO terms of MF source
simMatrix_MF <- calculateSimMatrix(placentaF_ordered_enriched$result$term_id,
                                orgdb = "org.Hs.eg.db",
                                ont = "MF",
                                method = "Rel")
## reduce the number of terms based on the similarity matrix for MF terms
reducedTerms_MF <- reduceSimMatrix(simMatrix_MF,
                                threshold = 0.85,
                                orgdb = "org.Hs.eg.db",
                                scores)
## add the source to table
reducedTerms_MF$source <- "MF"

## export reduced GO terms for visualisation
write.csv(reducedTerms_MF, file = file.path("/Users/taylaalbertini/Desktop/R studio/honours_project/fetal_comparison/enrichmentAnalysis_fetal.Rproj/raw_data/midF_sexspecific.csv"))
```

