---
title: "lung_f"
output: html_document
date: "2024-05-01"
---

# load libraries and set project directory
```{r}
# load the relevant libraries
library(plyr)
library(reshape2)
library(dplyr)
library(stringr)
library(readxl)
library(readr)
library(magrittr)
library(ggplot2)
library(edgeR)
library(limma)
library(Glimma)
library(RColorBrewer)

# set up project directory 
projDir <- "/Users/taylaalbertini/Desktop/R studio/honours_project/count_preprocessing/rawData"

# set path for counts tables 
import_SRR3191760 <- file.path(projDir, "lung_f/SRR3191760__GRCh38_ReadsPerGene_counts.tab")
import_SRR3192442 <- file.path(projDir, "lung_f/SRR3192442__GRCh38_ReadsPerGene_counts.tab")
import_SRR3192689 <- file.path(projDir, "lung_f/SRR3192689__GRCh38_ReadsPerGene_counts.tab")
import_SRR4421710 <- file.path(projDir, "lung_f/SRR4421710__GRCh38_ReadsPerGene_counts.tab")
import_SRR4421739 <- file.path(projDir, "lung_f/SRR4421739__GRCh38_ReadsPerGene_counts.tab")
```

# import raw readCounts
```{r}
# import the counts tables
## SRR3191760
SRR3191760 <- read_delim(file = import_SRR3191760,
                         col_names = FALSE,
                         delim = "\t") %>%
  as.data.frame() %>%
  dplyr::select(ensembl=X1,SRR3191760=X2)

## SRR3192442
SRR3192442 <- read_delim(file = import_SRR3192442,
                         col_names = FALSE,
                         delim = "\t") %>%
  as.data.frame() %>%
  dplyr::select(ensembl=X1,SRR3192442=X2)

## SRR3192689
SRR3192689 <- read_delim(file = import_SRR3192689,
                         col_names = FALSE,
                         delim = "\t") %>%
  as.data.frame() %>%
  dplyr::select(ensembl=X1,SRR3192689=X2)

## SRR4421710
SRR4421710 <- read_delim(file = import_SRR4421710,
                         col_names = FALSE,
                         delim = "\t") %>%
  as.data.frame() %>%
  dplyr::select(ensembl=X1,SRR4421710=X2)

## SRR4421739
SRR4421739 <- read_delim(file = import_SRR4421739,
                         col_names = FALSE,
                         delim = "\t") %>%
  as.data.frame() %>%
  dplyr::select(ensembl=X1,SRR4421739=X2)
```

# stitch samples together
```{r}
# join samples together 
## left joins the sample column by the 'ensembl' column
mergedCounts_lung_f <- dplyr::left_join(SRR3191760,SRR3192442, by="ensembl") %>%
  dplyr::left_join(.,SRR3192689, by="ensembl") %>%
  dplyr::left_join(.,SRR4421710, by="ensembl") %>%
  dplyr::left_join(.,SRR4421739, by="ensembl")

# remove rows with all zeros
mergedCounts_lung_f <- mergedCounts_lung_f[rowSums(mergedCounts_lung_f[,-1])>0,]

# convert 'ensembl' column to row names 
## ensure there are no row names first
rownames(mergedCounts_lung_f) <- NULL
mergedCounts_lung_f %<>% tibble::column_to_rownames("ensembl")
```

# library size scatter plot
```{r}
# create a small data frame with information for the plot
plotCounts_lung_f <- mergedCounts_lung_f %>%
  colSums(.) %>%
  as.data.frame() %>%
  tibble::rownames_to_column() %>%
  set_colnames(c("sample", "totalCounts")) %>%
  arrange(., totalCounts)

# make the plot
ggplot(data = plotCounts_lung_f,
       aes(x=reorder(sample, totalCounts),
           y=totalCounts,
           colour=totalCounts<9000000)) +

  geom_point(size=5) +
  scale_colour_manual(name='Read count\nthreshold',
                      values=setNames(c('red','green'),
                                      c(TRUE, FALSE))) +

  geom_hline(yintercept=9000000,
             show.legend=FALSE,
             linetype="dotted",
             colour="red") +


  ggtitle("Raw counts female lung") +
  theme_bw(base_size=16) +
  labs(title="Library size",
       subtitle="Raw mRNA read counts in female lung",
       x="Sample name",
       y="mRNA read counts") +
  
  theme(axis.text.x=element_text(angle=270,
                                 hjust=1.5,
                                 colour="black",
                                 size=12),

        axis.text.y = element_text(angle=0,
                                   colour="black",
                                   size=14))
```

# output file
```{r}
write.csv(mergedCounts_lung_f, file = file.path("/Users/taylaalbertini/Desktop/R studio/honours_project/fetal_comparison/readCounts_analysis/combined_raw/rawCounts_lung_f.csv"))
```


