---
title: "placenta_mid_f"
output: html_document
date: "2024-05-08"
---

# load libraries and set project directories 
```{r}
# load relevant libraries 
library(plyr)
library(reshape2)
library(dplyr)
library(stringr)
library(readxl)
library(readr)
library(magrittr)
library(ggplot2)
library(edgeR)
library(limma)
library(Glimma)
library(RColorBrewer)

# set up project directory 
projDir <- "/Users/taylaalbertini/Desktop/R studio/honours_project/count_preprocessing/rawData"

# set path for counts tables 
import_PAC_0101 <- file.path(projDir, "placenta_f/PAC_0101_T_S27__GRCh38_ReadsPerGene_counts.tab")
import_PAC_0110 <- file.path(projDir, "placenta_f/PAC_0110_T_S56__GRCh38_ReadsPerGene_counts.tab")
import_PAC_0113 <- file.path(projDir, "placenta_f/PAC_0113_T_S51__GRCh38_ReadsPerGene_counts.tab")
import_PAC_0121 <- file.path(projDir, "placenta_f/PAC_0121_T_S7__GRCh38_ReadsPerGene_counts.tab")
import_PAC_0126 <- file.path(projDir, "placenta_f/PAC_0126_T_S32__GRCh38_ReadsPerGene_counts.tab")
import_PAC_0135 <- file.path(projDir, "placenta_f/PAC_0135_T_S53__GRCh38_ReadsPerGene_counts.tab")
import_PAC017 <- file.path(projDir, "placenta_f/PAC017_RNA__GRCh38_ReadsPerGene_counts.tab")
import_PAC_0183 <- file.path(projDir, "placenta_f/PAC_0183_T_S78__GRCh38_ReadsPerGene_counts.tab")
import_PAC_0191 <- file.path(projDir, "placenta_f/PAC_0191_T_S29__GRCh38_ReadsPerGene_counts.tab")
import_PAC_0196 <- file.path(projDir, "placenta_f/PAC_0196_T_S30__GRCh38_ReadsPerGene_counts.tab")
import_PAC_0203 <- file.path(projDir, "placenta_f/PAC_0203_T_S54__GRCh38_ReadsPerGene_counts.tab")
import_PAC_0211 <- file.path(projDir, "placenta_f/PAC_0211_T_S28__GRCh38_ReadsPerGene_counts.tab")
import_PAC_0222 <- file.path(projDir, "placenta_f/PAC_0222_T_S81__GRCh38_ReadsPerGene_counts.tab")
import_PAC027 <- file.path(projDir, "placenta_f/PAC027_RNA__GRCh38_ReadsPerGene_counts.tab")
import_PAC033 <- file.path(projDir, "placenta_f/PAC033_RNA__GRCh38_ReadsPerGene_counts.tab")
import_PAC053 <- file.path(projDir, "placenta_f/PAC053_RNA__GRCh38_ReadsPerGene_counts.tab")
import_PAC058 <- file.path(projDir, "placenta_f/PAC058_RNA__GRCh38_ReadsPerGene_counts.tab")
import_PAC059 <- file.path(projDir, "placenta_f/PAC059_RNA__GRCh38_ReadsPerGene_counts.tab")
import_PAC071 <- file.path(projDir, "placenta_f/PAC071_RNA__GRCh38_ReadsPerGene_counts.tab")
import_PAC074 <- file.path(projDir, "placenta_f/PAC074_RNA__GRCh38_ReadsPerGene_counts.tab")
import_PAC078 <- file.path(projDir, "placenta_f/PAC078_RNA__GRCh38_ReadsPerGene_counts.tab")
import_PAC084 <- file.path(projDir, "placenta_f/PAC084_RNA__GRCh38_ReadsPerGene_counts.tab")
import_PAC097 <- file.path(projDir, "placenta_f/PAC097_RNA__GRCh38_ReadsPerGene_counts.tab")
import_PAC099 <- file.path(projDir, "placenta_f/PAC099_RNA__GRCh38_ReadsPerGene_counts.tab")
import_PAC100 <- file.path(projDir, "placenta_f/PAC100_RNA__GRCh38_ReadsPerGene_counts.tab")
import_PAC102 <- file.path(projDir, "placenta_f/PAC102_RNA__GRCh38_ReadsPerGene_counts.tab")
import_PAC105 <- file.path(projDir, "placenta_f/PAC105_RNA__GRCh38_ReadsPerGene_counts.tab")
import_PAC109 <- file.path(projDir, "placenta_f/PAC109_RNA__GRCh38_ReadsPerGene_counts.tab")
import_PAC111 <- file.path(projDir, "placenta_f/PAC111_RNA__GRCh38_ReadsPerGene_counts.tab")
import_PAC118 <- file.path(projDir, "placenta_f/PAC118_RNA__GRCh38_ReadsPerGene_counts.tab")
import_PAC124 <- file.path(projDir, "placenta_f/PAC124_RNA__GRCh38_ReadsPerGene_counts.tab")
import_PAC131 <- file.path(projDir, "placenta_f/PAC131_RNA__GRCh38_ReadsPerGene_counts.tab")
import_PAC134 <- file.path(projDir, "placenta_f/PAC134_RNA__GRCh38_ReadsPerGene_counts.tab")
import_PAC140 <- file.path(projDir, "placenta_f/PAC140_RNA__GRCh38_ReadsPerGene_counts.tab")
```

# import raw readCounts
```{r}
# import the count tables 
## PAC0101
PAC0101 <- read_delim(file = import_PAC_0101,
                         col_names = FALSE,
                         delim = "\t") %>%
  as.data.frame() %>%
  dplyr::select(ensembl=X1,PAC0101=X2)

## PAC0110
PAC0110 <- read_delim(file = import_PAC_0110,
                         col_names = FALSE,
                         delim = "\t") %>%
  as.data.frame() %>%
  dplyr::select(ensembl=X1,PAC0110=X2)

## PAC0113
PAC0113 <- read_delim(file = import_PAC_0113,
                         col_names = FALSE,
                         delim = "\t") %>%
  as.data.frame() %>%
  dplyr::select(ensembl=X1,PAC0113=X2)

## PAC0121
PAC0121 <- read_delim(file = import_PAC_0121,
                         col_names = FALSE,
                         delim = "\t") %>%
  as.data.frame() %>%
  dplyr::select(ensembl=X1,PAC0121=X2)

## PAC0126
PAC0126 <- read_delim(file = import_PAC_0126,
                         col_names = FALSE,
                         delim = "\t") %>%
  as.data.frame() %>%
  dplyr::select(ensembl=X1,PAC0126=X2)

## PAC0135
PAC0135 <- read_delim(file = import_PAC_0135,
                         col_names = FALSE,
                         delim = "\t") %>%
  as.data.frame() %>%
  dplyr::select(ensembl=X1,PAC0135=X2)

## PAC017
PAC017 <- read_delim(file = import_PAC017,
                         col_names = FALSE,
                         delim = "\t") %>%
  as.data.frame() %>%
  dplyr::select(ensembl=X1,PAC017=X2)

## PAC0183
PAC0183 <- read_delim(file = import_PAC_0183,
                         col_names = FALSE,
                         delim = "\t") %>%
  as.data.frame() %>%
  dplyr::select(ensembl=X1,PAC0183=X2)

## PAC0191
PAC0191 <- read_delim(file = import_PAC_0191,
                         col_names = FALSE,
                         delim = "\t") %>%
  as.data.frame() %>%
  dplyr::select(ensembl=X1,PAC0191=X2)

## PAC0196
PAC0196 <- read_delim(file = import_PAC_0196,
                         col_names = FALSE,
                         delim = "\t") %>%
  as.data.frame() %>%
  dplyr::select(ensembl=X1,PAC0196=X2)

## PAC0203
PAC0203 <- read_delim(file = import_PAC_0203,
                         col_names = FALSE,
                         delim = "\t") %>%
  as.data.frame() %>%
  dplyr::select(ensembl=X1,PAC0203=X2)

## PAC0110
PAC0211 <- read_delim(file = import_PAC_0211,
                         col_names = FALSE,
                         delim = "\t") %>%
  as.data.frame() %>%
  dplyr::select(ensembl=X1,PAC0211=X2)

## PAC0222
PAC0222 <- read_delim(file = import_PAC_0222,
                         col_names = FALSE,
                         delim = "\t") %>%
  as.data.frame() %>%
  dplyr::select(ensembl=X1,PAC0222=X2)

## PAC027
PAC027 <- read_delim(file = import_PAC027,
                         col_names = FALSE,
                         delim = "\t") %>%
  as.data.frame() %>%
  dplyr::select(ensembl=X1,PAC027=X2)

## PAC033
PAC033 <- read_delim(file = import_PAC033,
                         col_names = FALSE,
                         delim = "\t") %>%
  as.data.frame() %>%
  dplyr::select(ensembl=X1,PAC033=X2)

## PAC053
PAC053 <- read_delim(file = import_PAC053,
                         col_names = FALSE,
                         delim = "\t") %>%
  as.data.frame() %>%
  dplyr::select(ensembl=X1,PAC053=X2)

## PAC058
PAC058 <- read_delim(file = import_PAC058,
                         col_names = FALSE,
                         delim = "\t") %>%
  as.data.frame() %>%
  dplyr::select(ensembl=X1,PAC058=X2)

## PAC059
PAC059 <- read_delim(file = import_PAC059,
                         col_names = FALSE,
                         delim = "\t") %>%
  as.data.frame() %>%
  dplyr::select(ensembl=X1,PAC059=X2)

## PAC071
PAC071 <- read_delim(file = import_PAC071,
                         col_names = FALSE,
                         delim = "\t") %>%
  as.data.frame() %>%
  dplyr::select(ensembl=X1,PAC071=X2)

## PAC074
PAC074 <- read_delim(file = import_PAC074,
                         col_names = FALSE,
                         delim = "\t") %>%
  as.data.frame() %>%
  dplyr::select(ensembl=X1,PAC074=X2)

## PAC078
PAC078 <- read_delim(file = import_PAC078,
                         col_names = FALSE,
                         delim = "\t") %>%
  as.data.frame() %>%
  dplyr::select(ensembl=X1,PAC078=X2)

## PAC084
PAC084 <- read_delim(file = import_PAC084,
                         col_names = FALSE,
                         delim = "\t") %>%
  as.data.frame() %>%
  dplyr::select(ensembl=X1,PAC084=X2)

## PAC097
PAC097 <- read_delim(file = import_PAC097,
                         col_names = FALSE,
                         delim = "\t") %>%
  as.data.frame() %>%
  dplyr::select(ensembl=X1,PAC097=X2)

## PAC099
PAC099 <- read_delim(file = import_PAC099,
                         col_names = FALSE,
                         delim = "\t") %>%
  as.data.frame() %>%
  dplyr::select(ensembl=X1,PAC099=X2)

## PAC100
PAC100 <- read_delim(file = import_PAC100,
                         col_names = FALSE,
                         delim = "\t") %>%
  as.data.frame() %>%
  dplyr::select(ensembl=X1,PAC100=X2)

## PAC102
PAC102 <- read_delim(file = import_PAC102,
                         col_names = FALSE,
                         delim = "\t") %>%
  as.data.frame() %>%
  dplyr::select(ensembl=X1,PAC102=X2)

## PAC105
PAC105 <- read_delim(file = import_PAC105,
                         col_names = FALSE,
                         delim = "\t") %>%
  as.data.frame() %>%
  dplyr::select(ensembl=X1,PAC105=X2)

## PAC109
PAC109 <- read_delim(file = import_PAC109,
                         col_names = FALSE,
                         delim = "\t") %>%
  as.data.frame() %>%
  dplyr::select(ensembl=X1,PAC109=X2)

## PAC111
PAC111 <- read_delim(file = import_PAC111,
                         col_names = FALSE,
                         delim = "\t") %>%
  as.data.frame() %>%
  dplyr::select(ensembl=X1,PAC111=X2)

## PAC118
PAC118 <- read_delim(file = import_PAC118,
                         col_names = FALSE,
                         delim = "\t") %>%
  as.data.frame() %>%
  dplyr::select(ensembl=X1,PAC118=X2)

## PAC124
PAC124 <- read_delim(file = import_PAC124,
                         col_names = FALSE,
                         delim = "\t") %>%
  as.data.frame() %>%
  dplyr::select(ensembl=X1,PAC124=X2)

## PAC131
PAC131 <- read_delim(file = import_PAC131,
                         col_names = FALSE,
                         delim = "\t") %>%
  as.data.frame() %>%
  dplyr::select(ensembl=X1,PAC131=X2)

## PAC134
PAC134 <- read_delim(file = import_PAC134,
                         col_names = FALSE,
                         delim = "\t") %>%
  as.data.frame() %>%
  dplyr::select(ensembl=X1,PAC134=X2)

## PAC140
PAC140 <- read_delim(file = import_PAC140,
                         col_names = FALSE,
                         delim = "\t") %>%
  as.data.frame() %>%
  dplyr::select(ensembl=X1,PAC140=X2)
```

# stitch samples together
```{r}
# join samples together
## left joins the sample column by the 'ensembl' column
mergedCounts_placenta_f <- dplyr::left_join(PAC0101,PAC0110, by="ensembl") %>%
  dplyr::left_join(.,PAC0113, by="ensembl") %>%
  dplyr::left_join(.,PAC0121, by="ensembl") %>%
  dplyr::left_join(.,PAC0126, by="ensembl") %>%
  dplyr::left_join(.,PAC0135, by="ensembl") %>%
  dplyr::left_join(.,PAC017, by="ensembl") %>%
  dplyr::left_join(.,PAC0183, by="ensembl") %>%
  dplyr::left_join(.,PAC0191, by="ensembl") %>%
  dplyr::left_join(.,PAC0196, by="ensembl") %>%
  dplyr::left_join(.,PAC0203, by="ensembl") %>%
  dplyr::left_join(.,PAC0211, by="ensembl") %>%
  dplyr::left_join(.,PAC0222, by="ensembl") %>%
  dplyr::left_join(.,PAC027, by="ensembl") %>%
  dplyr::left_join(.,PAC033, by="ensembl") %>%
  dplyr::left_join(.,PAC053, by="ensembl") %>%
  dplyr::left_join(.,PAC058, by="ensembl") %>%
  dplyr::left_join(.,PAC059, by="ensembl") %>%
  dplyr::left_join(.,PAC071, by="ensembl") %>%
  dplyr::left_join(.,PAC074, by="ensembl") %>%
  dplyr::left_join(.,PAC078, by="ensembl") %>%
  dplyr::left_join(.,PAC084, by="ensembl") %>%
  dplyr::left_join(.,PAC097, by="ensembl") %>%
  dplyr::left_join(.,PAC099, by="ensembl") %>%
  dplyr::left_join(.,PAC100, by="ensembl") %>%
  dplyr::left_join(.,PAC102, by="ensembl") %>%
  dplyr::left_join(.,PAC105, by="ensembl") %>%
  dplyr::left_join(.,PAC109, by="ensembl") %>%
  dplyr::left_join(.,PAC111, by="ensembl") %>%
  dplyr::left_join(.,PAC118, by="ensembl") %>%
  dplyr::left_join(.,PAC124, by="ensembl") %>%
  dplyr::left_join(.,PAC131, by="ensembl") %>%
  dplyr::left_join(.,PAC134, by="ensembl") %>%
  dplyr::left_join(.,PAC140, by="ensembl")

# remove rows with all zeros
mergedCounts_placenta_f <- mergedCounts_placenta_f[rowSums(mergedCounts_placenta_f[,-1])>0,]

# convert 'ensembl' column to row names 
## ensure there are no row names first
rownames(mergedCounts_placenta_f) <- NULL
mergedCounts_placenta_f %<>% tibble::column_to_rownames("ensembl")
```

# library size scatter plot
```{r}
# create a small data frame with information for the plot
plotCounts_placenta_f <- mergedCounts_placenta_f %>%
  colSums(.) %>%
  as.data.frame() %>%
  tibble::rownames_to_column() %>%
  set_colnames(c("sample", "totalCounts")) %>%
  arrange(., totalCounts)

# make the plot
ggplot(data = plotCounts_placenta_f,
       aes(x=reorder(sample, totalCounts),
           y=totalCounts,
           colour=totalCounts<9000000)) +

  geom_point(size=5) +
  scale_colour_manual(name='Read count\nthreshold',
                      values=setNames(c('red','green'),
                                      c(TRUE, FALSE))) +

  geom_hline(yintercept=9000000,
             show.legend=FALSE,
             linetype="dotted",
             colour="red") +


  ggtitle("Raw counts female mid-gestation placenta") +
  theme_bw(base_size=16) +
  labs(title="Library size",
       subtitle="Raw mRNA read counts in female mid-gestation placenta",
       x="Sample name",
       y="mRNA read counts") +
  
  theme(axis.text.x=element_text(angle=270,
                                 hjust=1.5,
                                 colour="black",
                                 size=12),

        axis.text.y = element_text(angle=0,
                                   colour="black",
                                   size=14))
```

# output file
```{r}
write.csv(mergedCounts_placenta_f, file = file.path("/Users/taylaalbertini/Desktop/R studio/honours_project/fetal_comparison/readCounts_analysis/combined_raw/rawCounts_placenta_f.csv"))
```


