---
title: "placentaM_early_countsTable"
output: html_document
date: "2024-05-16"
---

# load libraries and set project directory 
```{r}
# load the relevant libraries 
library(plyr)
library(reshape2)
library(dplyr)
library(stringr)
library(readxl)
library(readr)
library(magrittr)
library(ggplot2)
library(edgeR)
library(limma)
library(Glimma)
library(RColorBrewer)

# set up project directory 
projDir <- "/Users/taylaalbertini/Desktop/R studio/honours_project/count_preprocessing/rawData/placenta_m"

# set path for counts tables 
import_PAC014 <- file.path(projDir, "PAC014_RNA__GRCh38_ReadsPerGene_counts.tab")
import_PAC_0141 <- file.path(projDir, "PAC_0141_T_S26__GRCh38_ReadsPerGene_counts.tab")
import_PAC_0186 <- file.path(projDir, "PAC_0186_T_S2__GRCh38_ReadsPerGene_counts.tab")
import_PAC_0198 <- file.path(projDir, "PAC_0198_T_S73__GRCh38_ReadsPerGene_counts.tab")
import_PAC_0202 <- file.path(projDir, "PAC_0202_T_S25__GRCh38_ReadsPerGene_counts.tab")
import_PAC_0204 <- file.path(projDir, "PAC_0204_T_S79__GRCh38_ReadsPerGene_counts.tab")
import_PAC_0214 <- file.path(projDir, "PAC_0214_T_S55__GRCh38_ReadsPerGene_counts.tab")
import_PAC025 <- file.path(projDir, "PAC025_RNA__GRCh38_ReadsPerGene_counts.tab")
import_PAC042 <- file.path(projDir, "PAC042_RNA__GRCh38_ReadsPerGene_counts.tab")
import_PAC044 <- file.path(projDir, "PAC044_RNA__GRCh38_ReadsPerGene_counts.tab")
import_PAC045 <- file.path(projDir, "PAC045_RNA__GRCh38_ReadsPerGene_counts.tab")
import_PAC048 <- file.path(projDir, "PAC048_RNA__GRCh38_ReadsPerGene_counts.tab")
import_PAC050 <- file.path(projDir, "PAC050_RNA__GRCh38_ReadsPerGene_counts.tab")
import_PAC052 <- file.path(projDir, "PAC052_RNA__GRCh38_ReadsPerGene_counts.tab")
import_PAC060 <- file.path(projDir, "PAC060_RNA__GRCh38_ReadsPerGene_counts.tab")
import_PAC063 <- file.path(projDir, "PAC063_RNA__GRCh38_ReadsPerGene_counts.tab")
import_PAC083 <- file.path(projDir, "PAC083_RNA__GRCh38_ReadsPerGene_counts.tab")
```

# import the raw counts
```{r}
# import the count tables 
## PAC014
PAC014 <- read_delim(file = import_PAC014,
                         col_names = FALSE,
                         delim = "\t") %>%
  as.data.frame() %>%
  dplyr::select(ensembl=X1,PAC014=X2)

## PAC0141
PAC0141 <- read_delim(file = import_PAC_0141,
                         col_names = FALSE,
                         delim = "\t") %>%
  as.data.frame() %>%
  dplyr::select(ensembl=X1,PAC0141=X2)

## PAC0186
PAC0186 <- read_delim(file = import_PAC_0186,
                         col_names = FALSE,
                         delim = "\t") %>%
  as.data.frame() %>%
  dplyr::select(ensembl=X1,PAC0186=X2)

## PAC0198
PAC0198 <- read_delim(file = import_PAC_0198,
                         col_names = FALSE,
                         delim = "\t") %>%
  as.data.frame() %>%
  dplyr::select(ensembl=X1,PAC0198=X2)

## PAC0202
PAC0202 <- read_delim(file = import_PAC_0202,
                         col_names = FALSE,
                         delim = "\t") %>%
  as.data.frame() %>%
  dplyr::select(ensembl=X1,PAC0202=X2)

## PAC0204
PAC0204 <- read_delim(file = import_PAC_0204,
                         col_names = FALSE,
                         delim = "\t") %>%
  as.data.frame() %>%
  dplyr::select(ensembl=X1,PAC0204=X2)

## PAC025
PAC025 <- read_delim(file = import_PAC025,
                         col_names = FALSE,
                         delim = "\t") %>%
  as.data.frame() %>%
  dplyr::select(ensembl=X1,PAC025=X2)

## PAC042
PAC042 <- read_delim(file = import_PAC042,
                         col_names = FALSE,
                         delim = "\t") %>%
  as.data.frame() %>%
  dplyr::select(ensembl=X1,PAC042=X2)

## PAC044
PAC044 <- read_delim(file = import_PAC044,
                         col_names = FALSE,
                         delim = "\t") %>%
  as.data.frame() %>%
  dplyr::select(ensembl=X1,PAC044=X2)

## PAC045
PAC045 <- read_delim(file = import_PAC045,
                         col_names = FALSE,
                         delim = "\t") %>%
  as.data.frame() %>%
  dplyr::select(ensembl=X1,PAC045=X2)

## PAC048
PAC048 <- read_delim(file = import_PAC048,
                         col_names = FALSE,
                         delim = "\t") %>%
  as.data.frame() %>%
  dplyr::select(ensembl=X1,PAC048=X2)

## PAC052
PAC052 <- read_delim(file = import_PAC052,
                         col_names = FALSE,
                         delim = "\t") %>%
  as.data.frame() %>%
  dplyr::select(ensembl=X1,PAC052=X2)

## PAC060
PAC060 <- read_delim(file = import_PAC060,
                         col_names = FALSE,
                         delim = "\t") %>%
  as.data.frame() %>%
  dplyr::select(ensembl=X1,PAC060=X2)

## PAC063
PAC063 <- read_delim(file = import_PAC063,
                         col_names = FALSE,
                         delim = "\t") %>%
  as.data.frame() %>%
  dplyr::select(ensembl=X1,PAC063=X2)

## PAC083
PAC083 <- read_delim(file = import_PAC083,
                         col_names = FALSE,
                         delim = "\t") %>%
  as.data.frame() %>%
  dplyr::select(ensembl=X1,PAC083=X2)
```

# stitch samples together
```{r}
# join the samples together into one table
## left joins the sample column by the 'ensembl' column
mergedCounts_placentaM_early <- dplyr::left_join(PAC014,PAC0141, by="ensembl") %>%
  dplyr::left_join(.,PAC0186, by="ensembl") %>%
  dplyr::left_join(.,PAC0198, by="ensembl") %>%
  dplyr::left_join(.,PAC0202, by="ensembl") %>%
  dplyr::left_join(.,PAC0204, by="ensembl") %>%
  dplyr::left_join(.,PAC025, by="ensembl") %>%
  dplyr::left_join(.,PAC042, by="ensembl") %>%
  dplyr::left_join(.,PAC044, by="ensembl") %>%
  dplyr::left_join(.,PAC045, by="ensembl") %>%
  dplyr::left_join(.,PAC048, by="ensembl") %>%
  dplyr::left_join(.,PAC052, by="ensembl") %>%
  dplyr::left_join(.,PAC060, by="ensembl") %>%
  dplyr::left_join(.,PAC063, by="ensembl") %>%
  dplyr::left_join(.,PAC083, by="ensembl")

# remove rows with all zeros
mergedCounts_placentaM_early <- mergedCounts_placentaM_early[rowSums(mergedCounts_placentaM_early[,-1])>0,]

# convert 'ensembl' column to row names 
## ensure there are no row names first
rownames(mergedCounts_placentaM_early) <- NULL
mergedCounts_placentaM_early %<>% tibble::column_to_rownames("ensembl")
```

# library scatter plot
```{r}
# create a small data frame with information for the plot
plotCounts_placentaM_early <- mergedCounts_placentaM_early %>%
  colSums(.) %>%
  as.data.frame() %>%
  tibble::rownames_to_column() %>%
  set_colnames(c("sample", "totalCounts")) %>%
  arrange(., totalCounts)

# make the plot
ggplot(data = plotCounts_placentaM_early,
       aes(x=reorder(sample, totalCounts),
           y=totalCounts,
           colour=totalCounts<9000000)) +

  geom_point(size=5) +
  scale_colour_manual(name='Read count\nthreshold',
                      values=setNames(c('red','green'),
                                      c(TRUE, FALSE))) +

  geom_hline(yintercept=9000000,
             show.legend=FALSE,
             linetype="dotted",
             colour="red") +


  ggtitle("Raw counts male early-gestation placenta male") +
  theme_bw(base_size=16) +
  labs(title="Library size",
       subtitle="Raw mRNA read counts in male early-gestation placenta",
       x="Sample name",
       y="mRNA read counts") +
  
  theme(axis.text.x=element_text(angle=270,
                                 hjust=1.5,
                                 colour="black",
                                 size=12),

        axis.text.y = element_text(angle=0,
                                   colour="black",
                                   size=14))
```

# output file
```{r}
write.csv(mergedCounts_placentaM_early, file = file.path("/Users/taylaalbertini/Desktop/R studio/honours_project/oxygen_threshold/rawData/rawCounts_placentaM_early.csv"))
```