---
title: "stomach_f"
output: html_document
date: "2024-05-01"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# load libraries
```{r}
library(plyr)
library(reshape2)
library(dplyr)
library(stringr)
library(readxl)
library(readr)
library(magrittr)
library(ggplot2)
library(edgeR)
library(limma)
library(Glimma)
library(RColorBrewer)

# set up project directory 
projDir <- "/Users/taylaalbertini/Desktop/R studio/honours_project/count_preprocessing/rawData"
import_SRR980483 <- file.path(projDir, "stomach_f/SRR980483__GRCh38_ReadsPerGene_counts.tab")
import_SRR3192450 <- file.path(projDir, "stomach_f/SRR3192450__GRCh38_ReadsPerGene_counts.tab")
import_SRR4421777 <- file.path(projDir, "stomach_f/SRR4421777__GRCh38_ReadsPerGene_counts.tab")
import_SRR5309855 <- file.path(projDir, "stomach_f/SRR5309855__GRCh38_ReadsPerGene_counts.tab")
import_SRR5309856 <- file.path(projDir, "stomach_f/SRR5309856__GRCh38_ReadsPerGene_counts.tab")
import_SRR5309881 <- file.path(projDir, "stomach_f/SRR5309881__GRCh38_ReadsPerGene_counts.tab")
```

# import read counts
```{r}
# import the counts tables
## SRR980483
SRR980483 <- read_delim(file = import_SRR980483,
                         col_names = FALSE,
                         delim = "\t") %>%
  as.data.frame() %>%
  dplyr::select(ensembl=X1,SRR980483=X2)

## SRR3192450
SRR3192450 <- read_delim(file = import_SRR3192450,
                         col_names = FALSE,
                         delim = "\t") %>%
  as.data.frame() %>%
  dplyr::select(ensembl=X1,SRR3192450=X2)

## SRR4421777
SRR4421777 <- read_delim(file = import_SRR4421777,
                         col_names = FALSE,
                         delim = "\t") %>%
  as.data.frame() %>%
  dplyr::select(ensembl=X1,SRR4421777=X2)

## SRR5309855
SRR5309855 <- read_delim(file = import_SRR5309855,
                         col_names = FALSE,
                         delim = "\t") %>%
  as.data.frame() %>%
  dplyr::select(ensembl=X1,SRR5309855=X2)

## SRR5309856
SRR5309856 <- read_delim(file = import_SRR5309856,
                         col_names = FALSE,
                         delim = "\t") %>%
  as.data.frame() %>%
  dplyr::select(ensembl=X1,SRR5309856=X2)

## SRR5309881
SRR5309881 <- read_delim(file = import_SRR5309881,
                         col_names = FALSE,
                         delim = "\t") %>%
  as.data.frame() %>%
  dplyr::select(ensembl=X1,SRR5309881=X2)
```

# stitch samples together
```{r}
mergedCounts_stomach_f <- dplyr::left_join(SRR980483,SRR3192450, by="ensembl") %>%
  dplyr::left_join(.,SRR4421777, by="ensembl") %>%
  dplyr::left_join(.,SRR5309855, by="ensembl") %>%
  dplyr::left_join(.,SRR5309856, by="ensembl") %>%
  dplyr::left_join(.,SRR5309881, by="ensembl") 

# remove rows with all zeros
mergedCounts_stomach_f <- mergedCounts_stomach_f[rowSums(mergedCounts_stomach_f[,-1])>0,]
rownames(mergedCounts_stomach_f) <- NULL
```

# remove the number after the period and convert ensembl to row nammes
```{r}
mergedCounts_stomach_f %<>% tidyr::separate(., col = ensembl, into = c("ensembl", "right")) %>%
  dplyr::select(., -right) %>%
  distinct(ensembl, .keep_all = TRUE) %>%
  tibble::column_to_rownames("ensembl")
```

# library size scatter plot
```{r}
# create a small data frame with information for the plot
plotCounts_stomach_f <- mergedCounts_stomach_f %>%
  colSums(.) %>%
  as.data.frame() %>%
  tibble::rownames_to_column() %>%
  set_colnames(c("sample", "totalCounts")) %>%
  arrange(., totalCounts)

# make the plot
ggplot(data = plotCounts_stomach_f,
       aes(x=reorder(sample, totalCounts),
           y=totalCounts,
           colour=totalCounts<9000000)) +

  geom_point(size=5) +
  scale_colour_manual(name='Read count\nthreshold',
                      values=setNames(c('red','green'),
                                      c(TRUE, FALSE))) +

  geom_hline(yintercept=9000000,
             show.legend=FALSE,
             linetype="dotted",
             colour="red") +


  ggtitle("Raw counts stomach female - all samples\n(hg38)") +
  theme_bw(base_size=16) +
  labs(title="Library size",
       subtitle="Raw mRNA read counts in stomach female",
       x="Sample name",
       y="mRNA read counts") +
  
  theme(axis.text.x=element_text(angle=270,
                                 hjust=1.5,
                                 colour="black",
                                 size=12),

        axis.text.y = element_text(angle=0,
                                   colour="black",
                                   size=14))
```
# create df excluding samples whcih FAIL library size threshold
```{r}
countsTable_stomach_f <- mergedCounts_stomach_f[,-(4:6)]
```

# output file
```{r}
write.csv(countsTable_stomach_f, file = file.path(projDir,
                                                 "combined_raw/rawCounts_stomach_f.csv"))
```
